create table studentinfo (
	roll_no INT,
	name VARCHAR(50),
	address VARCHAR(50),
	age INT
);
insert into studentinfo (roll_no, name, address, age) values (1, 'Knox', 'Room 1358', 21);
insert into studentinfo (roll_no, name, address, age) values (2, 'Marj', '1st Floor', null);
insert into studentinfo (roll_no, name, address, age) values (3, 'Cherice', 'PO Box 93264', 14);
insert into studentinfo (roll_no, name, address, age) values (4, 'Burty', '11th Floor', 18);
insert into studentinfo (roll_no, name, address, age) values (5, 'Adey', 'Room 365', 9);
insert into studentinfo (roll_no, name, address, age) values (6, 'Barney', '12th Floor', 14);
insert into studentinfo (roll_no, name, address, age) values (7, 'Rochette', 'Suite 45', 12);
insert into studentinfo (roll_no, name, address, age) values (8, 'Rafa', 'Suite 5', 13);
insert into studentinfo (roll_no, name, address, age) values (9, 'Gae', 'PO Box 71363', 18);
insert into studentinfo (roll_no, name, address, age) values (10, 'Kerrin', '5th Floor', 10);
insert into studentinfo (roll_no, name, address, age) values (11, 'Wilek', 'Suite 81', 20);
insert into studentinfo (roll_no, name, address, age) values (12, 'Imojean', 'PO Box 72024', 10);
insert into studentinfo (roll_no, name, address, age) values (13, 'Salome', 'Apt 1367', 12);
insert into studentinfo (roll_no, name, address, age) values (14, 'Charley', '19th Floor', 16);
insert into studentinfo (roll_no, name, address, age) values (15, 'Lamont', '14th Floor', 8);
insert into studentinfo (roll_no, name, address, age) values (16, 'Luise', '2nd Floor', 11);
insert into studentinfo (roll_no, name, address, age) values (17, 'Cordelie', 'PO Box 62631', 21);
insert into studentinfo (roll_no, name, address, age) values (18, 'Batsheva', 'Apt 843', 17);
insert into studentinfo (roll_no, name, address, age) values (19, 'Byram', '17th Floor', 9);
insert into studentinfo (roll_no, name, address, age) values (20, 'Wendye', 'PO Box 22402', 9);
insert into studentinfo (roll_no, name, address, age) values (21, 'Emmy', 'Room 622', 16);
insert into studentinfo (roll_no, name, address, age) values (22, 'Zackariah', 'Apt 1713', 9);
insert into studentinfo (roll_no, name, address, age) values (23, 'Kit', 'PO Box 98843', 16);
insert into studentinfo (roll_no, name, address, age) values (24, 'Emlyn', 'Suite 48', null);
insert into studentinfo (roll_no, name, address, age) values (25, 'Nell', '7th Floor', 16);
insert into studentinfo (roll_no, name, address, age) values (26, 'Angel', 'Suite 99', 17);
insert into studentinfo (roll_no, name, address, age) values (27, 'Lucas', 'Suite 37', 9);
insert into studentinfo (roll_no, name, address, age) values (28, 'Elly', '18th Floor', 19);
insert into studentinfo (roll_no, name, address, age) values (29, 'Maudie', 'Room 570', 22);
insert into studentinfo (roll_no, name, address, age) values (30, 'Maureene', 'Apt 644', 20);
insert into studentinfo (roll_no, name, address, age) values (31, 'Quinton', 'PO Box 71875', 12);
insert into studentinfo (roll_no, name, address, age) values (32, 'Winna', 'Room 1207', 22);
insert into studentinfo (roll_no, name, address, age) values (33, 'Carmen', 'Suite 96', 22);
insert into studentinfo (roll_no, name, address, age) values (34, 'Mada', '18th Floor', 20);
insert into studentinfo (roll_no, name, address, age) values (35, 'Byrom', '8th Floor', 11);
insert into studentinfo (roll_no, name, address, age) values (36, 'Wilie', 'Apt 372', 8);
insert into studentinfo (roll_no, name, address, age) values (37, 'Ethelin', 'Room 1122', 17);
insert into studentinfo (roll_no, name, address, age) values (38, 'Nancey', '12th Floor', 14);
insert into studentinfo (roll_no, name, address, age) values (39, 'Cordie', 'PO Box 47128', 9);
insert into studentinfo (roll_no, name, address, age) values (40, 'Jemima', 'Room 1344', 9);
insert into studentinfo (roll_no, name, address, age) values (41, 'Mayer', 'Apt 854', 24);
insert into studentinfo (roll_no, name, address, age) values (42, 'Conny', 'Room 748', 19);
insert into studentinfo (roll_no, name, address, age) values (43, 'Carr', '2nd Floor', 21);
insert into studentinfo (roll_no, name, address, age) values (44, 'Margery', 'Apt 168', 10);
insert into studentinfo (roll_no, name, address, age) values (45, 'Vi', 'Suite 1', 22);
insert into studentinfo (roll_no, name, address, age) values (46, 'Dody', 'Apt 298', 13);
insert into studentinfo (roll_no, name, address, age) values (47, 'Sherwynd', '1st Floor', 18);
insert into studentinfo (roll_no, name, address, age) values (48, 'Damian', 'PO Box 95052', 12);
insert into studentinfo (roll_no, name, address, age) values (49, 'Devlen', 'Apt 867', 14);
insert into studentinfo (roll_no, name, address, age) values (50, 'Granger', 'PO Box 56725', 18);
insert into studentinfo (roll_no, name, address, age) values (51, 'Portie', 'PO Box 89672', 6);
insert into studentinfo (roll_no, name, address, age) values (52, 'Ryun', 'Apt 1184', 18);
insert into studentinfo (roll_no, name, address, age) values (53, 'Rodolphe', 'Room 1466', 10);
insert into studentinfo (roll_no, name, address, age) values (54, 'Clemmie', 'Apt 155', 10);
insert into studentinfo (roll_no, name, address, age) values (55, 'Jamal', 'Apt 1985', 16);
insert into studentinfo (roll_no, name, address, age) values (56, 'Fonzie', '3rd Floor', 17);
insert into studentinfo (roll_no, name, address, age) values (57, 'Suzy', '19th Floor', 13);
insert into studentinfo (roll_no, name, address, age) values (58, 'Margette', 'Apt 1565', 17);
insert into studentinfo (roll_no, name, address, age) values (59, 'Marylin', 'Room 1281', 7);
insert into studentinfo (roll_no, name, address, age) values (60, 'Faydra', '20th Floor', 21);
insert into studentinfo (roll_no, name, address, age) values (61, 'Koenraad', '5th Floor', 21);
insert into studentinfo (roll_no, name, address, age) values (62, 'Somerset', '14th Floor', 7);
insert into studentinfo (roll_no, name, address, age) values (63, 'Paulo', '6th Floor', null);
insert into studentinfo (roll_no, name, address, age) values (64, 'Mersey', 'Suite 70', 22);
insert into studentinfo (roll_no, name, address, age) values (65, 'Smitty', 'PO Box 98421', 15);
insert into studentinfo (roll_no, name, address, age) values (66, 'Kristel', 'Apt 554', null);
insert into studentinfo (roll_no, name, address, age) values (67, 'Gabriella', 'Room 257', 23);
insert into studentinfo (roll_no, name, address, age) values (68, 'Chere', 'Room 1296', 6);
insert into studentinfo (roll_no, name, address, age) values (69, 'Rubin', '5th Floor', null);
insert into studentinfo (roll_no, name, address, age) values (70, 'Lanie', 'Apt 800', 11);
insert into studentinfo (roll_no, name, address, age) values (71, 'Lois', 'Apt 1595', 20);
insert into studentinfo (roll_no, name, address, age) values (72, 'Margalo', '7th Floor', 23);
insert into studentinfo (roll_no, name, address, age) values (73, 'Bernie', 'Apt 1271', 6);
insert into studentinfo (roll_no, name, address, age) values (74, 'Cherilynn', 'Suite 41', 16);
insert into studentinfo (roll_no, name, address, age) values (75, 'Raeann', 'PO Box 42488', 11);
insert into studentinfo (roll_no, name, address, age) values (76, 'Lauritz', 'Apt 1974', 12);
insert into studentinfo (roll_no, name, address, age) values (77, 'Klara', 'Suite 88', 15);
insert into studentinfo (roll_no, name, address, age) values (78, 'Marena', 'Room 990', 8);
insert into studentinfo (roll_no, name, address, age) values (79, 'Greggory', 'Apt 446', 8);
insert into studentinfo (roll_no, name, address, age) values (80, 'Sherye', 'PO Box 46315', 8);
insert into studentinfo (roll_no, name, address, age) values (81, 'Celine', 'Room 974', 23);
insert into studentinfo (roll_no, name, address, age) values (82, 'Vassily', 'Apt 1036', 10);
insert into studentinfo (roll_no, name, address, age) values (83, 'Hymie', 'PO Box 30334', 18);
insert into studentinfo (roll_no, name, address, age) values (84, 'Nathanial', 'PO Box 64010', 15);
insert into studentinfo (roll_no, name, address, age) values (85, 'Gale', '9th Floor', 14);
insert into studentinfo (roll_no, name, address, age) values (86, 'Verina', 'Room 818', 11);
insert into studentinfo (roll_no, name, address, age) values (87, 'Mathe', '17th Floor', 14);
insert into studentinfo (roll_no, name, address, age) values (88, 'Gordy', 'Suite 73', 14);
insert into studentinfo (roll_no, name, address, age) values (89, 'Robinetta', 'Room 786', 7);
insert into studentinfo (roll_no, name, address, age) values (90, 'Corilla', 'Apt 852', 22);
insert into studentinfo (roll_no, name, address, age) values (91, 'Henrie', 'Apt 1469', 8);
insert into studentinfo (roll_no, name, address, age) values (92, 'Dianne', 'PO Box 74731', null);
insert into studentinfo (roll_no, name, address, age) values (93, 'Lethia', 'Suite 17', 16);
insert into studentinfo (roll_no, name, address, age) values (94, 'Robinett', '11th Floor', 15);
insert into studentinfo (roll_no, name, address, age) values (95, 'Merline', 'Room 1232', 6);
insert into studentinfo (roll_no, name, address, age) values (96, 'Pattie', 'Suite 32', 14);
insert into studentinfo (roll_no, name, address, age) values (97, 'Winni', 'Apt 1455', 19);
insert into studentinfo (roll_no, name, address, age) values (98, 'Lindsay', 'Room 1855', 13);
insert into studentinfo (roll_no, name, address, age) values (99, 'Ruby', 'Suite 57', 18);
insert into studentinfo (roll_no, name, address, age) values (100, 'Junette', 'PO Box 12125', 8);
insert into studentinfo (roll_no, name, address, age) values (101, 'Koral', 'PO Box 70872', 20);
insert into studentinfo (roll_no, name, address, age) values (102, 'Eldin', 'Room 1514', null);
insert into studentinfo (roll_no, name, address, age) values (103, 'Rey', 'Apt 1963', 19);
insert into studentinfo (roll_no, name, address, age) values (104, 'Raimundo', '12th Floor', 8);
insert into studentinfo (roll_no, name, address, age) values (105, 'Emmott', 'Room 113', 20);
insert into studentinfo (roll_no, name, address, age) values (106, 'Kylynn', 'PO Box 69624', 23);
insert into studentinfo (roll_no, name, address, age) values (107, 'Tedi', 'PO Box 54076', null);
insert into studentinfo (roll_no, name, address, age) values (108, 'Yale', 'PO Box 78883', 14);
insert into studentinfo (roll_no, name, address, age) values (109, 'Elna', 'Suite 22', 15);
insert into studentinfo (roll_no, name, address, age) values (110, 'Armand', '14th Floor', 8);
insert into studentinfo (roll_no, name, address, age) values (111, 'Shurlocke', 'Suite 97', 23);
insert into studentinfo (roll_no, name, address, age) values (112, 'Sissy', 'PO Box 58209', 24);
insert into studentinfo (roll_no, name, address, age) values (113, 'Brendin', '1st Floor', 21);
insert into studentinfo (roll_no, name, address, age) values (114, 'Dunstan', 'PO Box 75866', 14);
insert into studentinfo (roll_no, name, address, age) values (115, 'Nathanael', 'PO Box 38449', 10);
insert into studentinfo (roll_no, name, address, age) values (116, 'Thomas', '20th Floor', null);
insert into studentinfo (roll_no, name, address, age) values (117, 'Rosemary', 'Suite 42', 11);
insert into studentinfo (roll_no, name, address, age) values (118, 'Hope', 'PO Box 13726', 22);
insert into studentinfo (roll_no, name, address, age) values (119, 'Corrie', 'Suite 50', 20);
insert into studentinfo (roll_no, name, address, age) values (120, 'Rhodie', 'Suite 53', null);
insert into studentinfo (roll_no, name, address, age) values (121, 'Parnell', '13th Floor', 14);
insert into studentinfo (roll_no, name, address, age) values (122, 'Morgana', 'Apt 1629', 12);
insert into studentinfo (roll_no, name, address, age) values (123, 'Hobart', 'PO Box 61842', 22);
insert into studentinfo (roll_no, name, address, age) values (124, 'Emery', 'Room 756', 13);
insert into studentinfo (roll_no, name, address, age) values (125, 'Bernette', '12th Floor', 23);
insert into studentinfo (roll_no, name, address, age) values (126, 'Augusta', 'Apt 456', 13);
insert into studentinfo (roll_no, name, address, age) values (127, 'Kim', 'PO Box 42922', 21);
insert into studentinfo (roll_no, name, address, age) values (128, 'Arleta', '3rd Floor', 15);
insert into studentinfo (roll_no, name, address, age) values (129, 'Glenn', 'Room 1576', 10);
insert into studentinfo (roll_no, name, address, age) values (130, 'Jeramey', 'PO Box 72489', 18);
insert into studentinfo (roll_no, name, address, age) values (131, 'Dehlia', 'Suite 19', 11);
insert into studentinfo (roll_no, name, address, age) values (132, 'Bale', 'Apt 935', 17);
insert into studentinfo (roll_no, name, address, age) values (133, 'Mildred', 'Room 1532', 19);
insert into studentinfo (roll_no, name, address, age) values (134, 'Teddie', 'PO Box 16479', null);
insert into studentinfo (roll_no, name, address, age) values (135, 'Currie', 'PO Box 68460', 19);
insert into studentinfo (roll_no, name, address, age) values (136, 'Sauncho', 'Apt 927', 18);
insert into studentinfo (roll_no, name, address, age) values (137, 'Hermine', '20th Floor', 23);
insert into studentinfo (roll_no, name, address, age) values (138, 'Rycca', 'Suite 58', 6);
insert into studentinfo (roll_no, name, address, age) values (139, 'Pattin', 'Room 1890', 10);
insert into studentinfo (roll_no, name, address, age) values (140, 'Ellery', 'Apt 1402', 8);
insert into studentinfo (roll_no, name, address, age) values (141, 'Joellen', 'PO Box 33940', 10);
insert into studentinfo (roll_no, name, address, age) values (142, 'Hank', 'Room 1417', 9);
insert into studentinfo (roll_no, name, address, age) values (143, 'Marius', '11th Floor', 16);
insert into studentinfo (roll_no, name, address, age) values (144, 'Israel', '14th Floor', 18);
insert into studentinfo (roll_no, name, address, age) values (145, 'Cheslie', 'Suite 77', 22);
insert into studentinfo (roll_no, name, address, age) values (146, 'Jodie', 'Room 859', 6);
insert into studentinfo (roll_no, name, address, age) values (147, 'Theodoric', '4th Floor', 12);
insert into studentinfo (roll_no, name, address, age) values (148, 'Averil', 'Room 123', 8);
insert into studentinfo (roll_no, name, address, age) values (149, 'Rodi', '20th Floor', 19);
insert into studentinfo (roll_no, name, address, age) values (150, 'Krishna', 'Suite 24', 18);
insert into studentinfo (roll_no, name, address, age) values (151, 'Gianna', 'PO Box 9873', null);
insert into studentinfo (roll_no, name, address, age) values (152, 'Mylo', '18th Floor', 14);
insert into studentinfo (roll_no, name, address, age) values (153, 'Roch', '10th Floor', 18);
insert into studentinfo (roll_no, name, address, age) values (154, 'Robbie', 'Suite 61', 23);
insert into studentinfo (roll_no, name, address, age) values (155, 'Larissa', 'Room 1577', 20);
insert into studentinfo (roll_no, name, address, age) values (156, 'Annalise', 'Room 409', 24);
insert into studentinfo (roll_no, name, address, age) values (157, 'Giulietta', 'Room 1407', 17);
insert into studentinfo (roll_no, name, address, age) values (158, 'Lynnett', 'Room 494', 20);
insert into studentinfo (roll_no, name, address, age) values (159, 'Bobine', 'Room 882', 23);
insert into studentinfo (roll_no, name, address, age) values (160, 'Rory', 'PO Box 75124', null);
insert into studentinfo (roll_no, name, address, age) values (161, 'Joy', 'Room 1068', null);
insert into studentinfo (roll_no, name, address, age) values (162, 'Reube', 'Suite 48', 19);
insert into studentinfo (roll_no, name, address, age) values (163, 'Tillie', 'Room 685', 8);
insert into studentinfo (roll_no, name, address, age) values (164, 'Ase', 'Suite 36', 20);
insert into studentinfo (roll_no, name, address, age) values (165, 'Lamar', 'Room 156', 16);
insert into studentinfo (roll_no, name, address, age) values (166, 'Donetta', 'Apt 892', 24);
insert into studentinfo (roll_no, name, address, age) values (167, 'Allyn', '4th Floor', 22);
insert into studentinfo (roll_no, name, address, age) values (168, 'Fidela', 'Apt 1284', 16);
insert into studentinfo (roll_no, name, address, age) values (169, 'Giovanni', 'PO Box 66304', 9);
insert into studentinfo (roll_no, name, address, age) values (170, 'Alane', 'Apt 912', null);
insert into studentinfo (roll_no, name, address, age) values (171, 'Roland', 'PO Box 6228', 16);
insert into studentinfo (roll_no, name, address, age) values (172, 'Corina', 'Room 82', 14);
insert into studentinfo (roll_no, name, address, age) values (173, 'Berget', '14th Floor', 20);
insert into studentinfo (roll_no, name, address, age) values (174, 'Gaven', '7th Floor', 22);
insert into studentinfo (roll_no, name, address, age) values (175, 'Washington', 'Apt 940', 18);
insert into studentinfo (roll_no, name, address, age) values (176, 'Harold', '6th Floor', 12);
insert into studentinfo (roll_no, name, address, age) values (177, 'Raeann', 'Suite 72', 17);
insert into studentinfo (roll_no, name, address, age) values (178, 'Teressa', '11th Floor', 22);
insert into studentinfo (roll_no, name, address, age) values (179, 'Sky', 'Room 1090', 19);
insert into studentinfo (roll_no, name, address, age) values (180, 'Wynn', 'Apt 1183', 11);
insert into studentinfo (roll_no, name, address, age) values (181, 'Kizzie', 'Room 915', 7);
insert into studentinfo (roll_no, name, address, age) values (182, 'Brunhilda', 'Room 54', 8);
insert into studentinfo (roll_no, name, address, age) values (183, 'Hilary', 'PO Box 84907', 19);
insert into studentinfo (roll_no, name, address, age) values (184, 'Lebbie', 'Apt 164', 11);
insert into studentinfo (roll_no, name, address, age) values (185, 'Chandra', 'Apt 1796', 8);
insert into studentinfo (roll_no, name, address, age) values (186, 'Marve', 'Apt 425', 21);
insert into studentinfo (roll_no, name, address, age) values (187, 'Jodee', 'Suite 58', 13);
insert into studentinfo (roll_no, name, address, age) values (188, 'Merline', 'Room 1898', 19);
insert into studentinfo (roll_no, name, address, age) values (189, 'Joelle', 'Suite 41', null);
insert into studentinfo (roll_no, name, address, age) values (190, 'Aland', 'Room 1934', 22);
insert into studentinfo (roll_no, name, address, age) values (191, 'Starr', 'Suite 12', 9);
insert into studentinfo (roll_no, name, address, age) values (192, 'Bennie', 'PO Box 84728', 9);
insert into studentinfo (roll_no, name, address, age) values (193, 'Cairistiona', 'Suite 74', null);
insert into studentinfo (roll_no, name, address, age) values (194, 'Lek', 'Suite 15', 17);
insert into studentinfo (roll_no, name, address, age) values (195, 'Kahaleel', '20th Floor', 10);
insert into studentinfo (roll_no, name, address, age) values (196, 'Quentin', '18th Floor', 14);
insert into studentinfo (roll_no, name, address, age) values (197, 'Richardo', 'Suite 76', 21);
insert into studentinfo (roll_no, name, address, age) values (198, 'Udall', '4th Floor', 21);
insert into studentinfo (roll_no, name, address, age) values (199, 'Kaitlyn', '18th Floor', 18);
insert into studentinfo (roll_no, name, address, age) values (200, 'Hort', '2nd Floor', 19);
insert into studentinfo (roll_no, name, address, age) values (201, 'Domenico', 'Apt 1773', 7);
insert into studentinfo (roll_no, name, address, age) values (202, 'Jud', 'Apt 746', 23);
insert into studentinfo (roll_no, name, address, age) values (203, 'Martita', 'Apt 1221', 13);
insert into studentinfo (roll_no, name, address, age) values (204, 'Chrystel', 'Apt 17', 11);
insert into studentinfo (roll_no, name, address, age) values (205, 'Abbie', 'Apt 536', 24);
insert into studentinfo (roll_no, name, address, age) values (206, 'Phebe', '18th Floor', 9);
insert into studentinfo (roll_no, name, address, age) values (207, 'Rowena', 'Suite 53', 9);
insert into studentinfo (roll_no, name, address, age) values (208, 'Rurik', 'Suite 27', 23);
insert into studentinfo (roll_no, name, address, age) values (209, 'Pietro', 'Suite 62', 16);
insert into studentinfo (roll_no, name, address, age) values (210, 'Maye', 'Apt 451', 9);
insert into studentinfo (roll_no, name, address, age) values (211, 'Beitris', 'Suite 43', 12);
insert into studentinfo (roll_no, name, address, age) values (212, 'Jillian', 'Apt 1383', 21);
insert into studentinfo (roll_no, name, address, age) values (213, 'Christie', 'PO Box 54618', 14);
insert into studentinfo (roll_no, name, address, age) values (214, 'Stefan', 'Room 132', 16);
insert into studentinfo (roll_no, name, address, age) values (215, 'Christal', 'PO Box 41661', 6);
insert into studentinfo (roll_no, name, address, age) values (216, 'Kamillah', 'Room 494', 7);
insert into studentinfo (roll_no, name, address, age) values (217, 'Hurleigh', 'Room 898', 19);
insert into studentinfo (roll_no, name, address, age) values (218, 'Eleanor', 'Apt 1668', 18);
insert into studentinfo (roll_no, name, address, age) values (219, 'Agata', 'Suite 34', 24);
insert into studentinfo (roll_no, name, address, age) values (220, 'Syman', 'Suite 13', 7);
insert into studentinfo (roll_no, name, address, age) values (221, 'Ruthann', 'Apt 540', 14);
insert into studentinfo (roll_no, name, address, age) values (222, 'Paxon', 'Apt 532', 22);
insert into studentinfo (roll_no, name, address, age) values (223, 'Harper', 'Room 841', 14);
insert into studentinfo (roll_no, name, address, age) values (224, 'Curtice', 'PO Box 52331', 22);
insert into studentinfo (roll_no, name, address, age) values (225, 'Zoe', 'Suite 27', 12);
insert into studentinfo (roll_no, name, address, age) values (226, 'Tonnie', 'Suite 80', null);
insert into studentinfo (roll_no, name, address, age) values (227, 'Jennie', '7th Floor', 17);
insert into studentinfo (roll_no, name, address, age) values (228, 'Field', 'Suite 74', 21);
insert into studentinfo (roll_no, name, address, age) values (229, 'Philly', 'Apt 1764', null);
insert into studentinfo (roll_no, name, address, age) values (230, 'Anastasia', 'Room 834', 22);
insert into studentinfo (roll_no, name, address, age) values (231, 'Ashley', 'PO Box 10348', 19);
insert into studentinfo (roll_no, name, address, age) values (232, 'Emili', '16th Floor', 23);
insert into studentinfo (roll_no, name, address, age) values (233, 'Nye', 'Apt 227', null);
insert into studentinfo (roll_no, name, address, age) values (234, 'Susanne', 'PO Box 49948', 20);
insert into studentinfo (roll_no, name, address, age) values (235, 'Maria', 'PO Box 63246', 17);
insert into studentinfo (roll_no, name, address, age) values (236, 'Michaelina', 'Suite 19', 20);
insert into studentinfo (roll_no, name, address, age) values (237, 'Lincoln', 'Apt 98', 23);
insert into studentinfo (roll_no, name, address, age) values (238, 'Dexter', 'Room 1539', 11);
insert into studentinfo (roll_no, name, address, age) values (239, 'Valerie', '11th Floor', 15);
insert into studentinfo (roll_no, name, address, age) values (240, 'Candra', 'Suite 94', 15);
insert into studentinfo (roll_no, name, address, age) values (241, 'Isidor', 'PO Box 35649', null);
insert into studentinfo (roll_no, name, address, age) values (242, 'Ilysa', 'Apt 1578', 6);
insert into studentinfo (roll_no, name, address, age) values (243, 'Clem', 'Suite 77', 19);
insert into studentinfo (roll_no, name, address, age) values (244, 'Eal', 'Room 571', 14);
insert into studentinfo (roll_no, name, address, age) values (245, 'Harv', 'PO Box 31276', 10);
insert into studentinfo (roll_no, name, address, age) values (246, 'Stephie', 'PO Box 64596', 14);
insert into studentinfo (roll_no, name, address, age) values (247, 'Jeana', 'Apt 68', 20);
insert into studentinfo (roll_no, name, address, age) values (248, 'Jeremiah', 'Suite 24', null);
insert into studentinfo (roll_no, name, address, age) values (249, 'Shana', '16th Floor', null);
insert into studentinfo (roll_no, name, address, age) values (250, 'Trenna', 'Apt 1895', 10);
insert into studentinfo (roll_no, name, address, age) values (251, 'Olympie', 'Suite 27', 13);
insert into studentinfo (roll_no, name, address, age) values (252, 'Max', 'PO Box 32346', 22);
insert into studentinfo (roll_no, name, address, age) values (253, 'Rufus', 'Room 350', 10);
insert into studentinfo (roll_no, name, address, age) values (254, 'Winn', 'PO Box 53438', 18);
insert into studentinfo (roll_no, name, address, age) values (255, 'Lindsay', 'Room 550', 14);
insert into studentinfo (roll_no, name, address, age) values (256, 'Edmund', 'Suite 60', 13);
insert into studentinfo (roll_no, name, address, age) values (257, 'Veronique', 'Apt 307', 8);
insert into studentinfo (roll_no, name, address, age) values (258, 'Sharia', 'Room 959', 23);
insert into studentinfo (roll_no, name, address, age) values (259, 'Marja', 'PO Box 24002', 15);
insert into studentinfo (roll_no, name, address, age) values (260, 'Pryce', 'Suite 96', 11);
insert into studentinfo (roll_no, name, address, age) values (261, 'Odell', 'Room 1648', 18);
insert into studentinfo (roll_no, name, address, age) values (262, 'Ashlan', '16th Floor', 14);
insert into studentinfo (roll_no, name, address, age) values (263, 'Dasha', 'Apt 830', 21);
insert into studentinfo (roll_no, name, address, age) values (264, 'Matias', 'Suite 48', 16);
insert into studentinfo (roll_no, name, address, age) values (265, 'Inna', 'Apt 904', 14);
insert into studentinfo (roll_no, name, address, age) values (266, 'Thadeus', 'Room 1641', 22);
insert into studentinfo (roll_no, name, address, age) values (267, 'Corabel', '14th Floor', 23);
insert into studentinfo (roll_no, name, address, age) values (268, 'Chrisse', 'Apt 1549', 11);
insert into studentinfo (roll_no, name, address, age) values (269, 'Florella', 'Apt 1219', 14);
insert into studentinfo (roll_no, name, address, age) values (270, 'Harmony', 'PO Box 55316', 15);
insert into studentinfo (roll_no, name, address, age) values (271, 'Francoise', 'Suite 9', 10);
insert into studentinfo (roll_no, name, address, age) values (272, 'Vilma', '18th Floor', 22);
insert into studentinfo (roll_no, name, address, age) values (273, 'Kirbie', 'Room 370', null);
insert into studentinfo (roll_no, name, address, age) values (274, 'Howey', 'Suite 94', 18);
insert into studentinfo (roll_no, name, address, age) values (275, 'Taite', 'Apt 967', 19);
insert into studentinfo (roll_no, name, address, age) values (276, 'Betty', 'Suite 91', 15);
insert into studentinfo (roll_no, name, address, age) values (277, 'Abie', 'Room 1502', 15);
insert into studentinfo (roll_no, name, address, age) values (278, 'Beryle', '15th Floor', 24);
insert into studentinfo (roll_no, name, address, age) values (279, 'Cherey', 'Room 1461', 16);
insert into studentinfo (roll_no, name, address, age) values (280, 'Burlie', 'Room 475', 15);
insert into studentinfo (roll_no, name, address, age) values (281, 'Clotilda', 'Apt 1562', 17);
insert into studentinfo (roll_no, name, address, age) values (282, 'Nanette', 'Suite 5', null);
insert into studentinfo (roll_no, name, address, age) values (283, 'Fayina', 'PO Box 55563', 18);
insert into studentinfo (roll_no, name, address, age) values (284, 'Cecilia', 'Apt 411', 19);
insert into studentinfo (roll_no, name, address, age) values (285, 'Sybila', 'Room 1568', 16);
insert into studentinfo (roll_no, name, address, age) values (286, 'Thornton', '4th Floor', 23);
insert into studentinfo (roll_no, name, address, age) values (287, 'Issiah', 'Room 453', 9);
insert into studentinfo (roll_no, name, address, age) values (288, 'Forrester', '3rd Floor', 18);
insert into studentinfo (roll_no, name, address, age) values (289, 'Margret', 'Apt 223', 14);
insert into studentinfo (roll_no, name, address, age) values (290, 'Tabina', 'Apt 705', null);
insert into studentinfo (roll_no, name, address, age) values (291, 'Rosalia', 'Apt 1223', 7);
insert into studentinfo (roll_no, name, address, age) values (292, 'Diarmid', 'PO Box 18680', 21);
insert into studentinfo (roll_no, name, address, age) values (293, 'Rona', 'Room 654', 17);
insert into studentinfo (roll_no, name, address, age) values (294, 'Paxton', 'PO Box 2151', 14);
insert into studentinfo (roll_no, name, address, age) values (295, 'Eleonore', 'Suite 85', 11);
insert into studentinfo (roll_no, name, address, age) values (296, 'Frasquito', 'PO Box 47349', 21);
insert into studentinfo (roll_no, name, address, age) values (297, 'Margery', '9th Floor', 8);
insert into studentinfo (roll_no, name, address, age) values (298, 'Dyanne', 'Apt 1816', 16);
insert into studentinfo (roll_no, name, address, age) values (299, 'Paolo', 'Apt 95', null);
insert into studentinfo (roll_no, name, address, age) values (300, 'Shirlene', 'Suite 37', 6);
insert into studentinfo (roll_no, name, address, age) values (301, 'Ulises', 'Room 1112', 10);
insert into studentinfo (roll_no, name, address, age) values (302, 'Laurette', 'Apt 1741', 12);
insert into studentinfo (roll_no, name, address, age) values (303, 'Salli', 'Room 1325', 8);
insert into studentinfo (roll_no, name, address, age) values (304, 'Aurelea', 'Room 1748', 15);
insert into studentinfo (roll_no, name, address, age) values (305, 'Maegan', 'PO Box 15308', 6);
insert into studentinfo (roll_no, name, address, age) values (306, 'Tedda', 'Apt 1086', 13);
insert into studentinfo (roll_no, name, address, age) values (307, 'Lottie', 'Room 1845', 20);
insert into studentinfo (roll_no, name, address, age) values (308, 'Constantina', 'Room 1438', null);
insert into studentinfo (roll_no, name, address, age) values (309, 'Rina', '5th Floor', 19);
insert into studentinfo (roll_no, name, address, age) values (310, 'Farly', 'Apt 28', 12);
insert into studentinfo (roll_no, name, address, age) values (311, 'Yehudit', '15th Floor', 6);
insert into studentinfo (roll_no, name, address, age) values (312, 'Goldi', 'Room 870', 7);
insert into studentinfo (roll_no, name, address, age) values (313, 'Enrique', 'Room 807', 17);
insert into studentinfo (roll_no, name, address, age) values (314, 'Ardelle', 'Suite 76', 18);
insert into studentinfo (roll_no, name, address, age) values (315, 'Florance', 'Suite 72', 19);
insert into studentinfo (roll_no, name, address, age) values (316, 'Gonzalo', 'Apt 17', null);
insert into studentinfo (roll_no, name, address, age) values (317, 'Kira', 'PO Box 77888', 17);
insert into studentinfo (roll_no, name, address, age) values (318, 'Beltran', 'Apt 1338', 7);
insert into studentinfo (roll_no, name, address, age) values (319, 'Alicia', 'Suite 83', 19);
insert into studentinfo (roll_no, name, address, age) values (320, 'Jackquelin', 'Apt 73', 13);
insert into studentinfo (roll_no, name, address, age) values (321, 'Roberta', 'Room 422', 20);
insert into studentinfo (roll_no, name, address, age) values (322, 'Zollie', '1st Floor', null);
insert into studentinfo (roll_no, name, address, age) values (323, 'Karissa', '8th Floor', 19);
insert into studentinfo (roll_no, name, address, age) values (324, 'Lynette', 'Room 1979', 15);
insert into studentinfo (roll_no, name, address, age) values (325, 'Georgena', 'Apt 1449', 17);
insert into studentinfo (roll_no, name, address, age) values (326, 'Barri', 'Suite 5', 16);
insert into studentinfo (roll_no, name, address, age) values (327, 'Jeffy', '9th Floor', 20);
insert into studentinfo (roll_no, name, address, age) values (328, 'Glyn', 'Suite 99', 14);
insert into studentinfo (roll_no, name, address, age) values (329, 'Meridel', 'Apt 171', 9);
insert into studentinfo (roll_no, name, address, age) values (330, 'Tallie', 'PO Box 57529', 9);
insert into studentinfo (roll_no, name, address, age) values (331, 'Gale', '10th Floor', 14);
insert into studentinfo (roll_no, name, address, age) values (332, 'Chiquita', 'PO Box 97144', 24);
insert into studentinfo (roll_no, name, address, age) values (333, 'Cyndie', 'PO Box 36478', 23);
insert into studentinfo (roll_no, name, address, age) values (334, 'Laurella', 'Room 1636', 21);
insert into studentinfo (roll_no, name, address, age) values (335, 'Joellen', '18th Floor', 24);
insert into studentinfo (roll_no, name, address, age) values (336, 'Cammie', 'Apt 540', 20);
insert into studentinfo (roll_no, name, address, age) values (337, 'Sisely', 'Apt 1588', 7);
insert into studentinfo (roll_no, name, address, age) values (338, 'Cassandra', 'Apt 431', 10);
insert into studentinfo (roll_no, name, address, age) values (339, 'Nana', '9th Floor', 15);
insert into studentinfo (roll_no, name, address, age) values (340, 'Gregorius', 'PO Box 18473', 12);
insert into studentinfo (roll_no, name, address, age) values (341, 'Alon', 'PO Box 88248', 15);
insert into studentinfo (roll_no, name, address, age) values (342, 'Alfy', '11th Floor', null);
insert into studentinfo (roll_no, name, address, age) values (343, 'Alaine', 'Suite 79', null);
insert into studentinfo (roll_no, name, address, age) values (344, 'Myrwyn', 'PO Box 36656', 9);
insert into studentinfo (roll_no, name, address, age) values (345, 'Randie', 'Suite 66', 14);
insert into studentinfo (roll_no, name, address, age) values (346, 'Leticia', 'Apt 1513', 14);
insert into studentinfo (roll_no, name, address, age) values (347, 'Alexandrina', '20th Floor', 23);
insert into studentinfo (roll_no, name, address, age) values (348, 'Tove', 'Apt 708', null);
insert into studentinfo (roll_no, name, address, age) values (349, 'Binky', 'Room 1768', 14);
insert into studentinfo (roll_no, name, address, age) values (350, 'Pollyanna', 'PO Box 69399', 21);
insert into studentinfo (roll_no, name, address, age) values (351, 'Golda', 'Apt 508', 10);
insert into studentinfo (roll_no, name, address, age) values (352, 'Roshelle', '18th Floor', 13);
insert into studentinfo (roll_no, name, address, age) values (353, 'Augusto', '19th Floor', 23);
insert into studentinfo (roll_no, name, address, age) values (354, 'Mallorie', 'Room 1543', 23);
insert into studentinfo (roll_no, name, address, age) values (355, 'Marita', '2nd Floor', 15);
insert into studentinfo (roll_no, name, address, age) values (356, 'Carita', 'Room 1184', 9);
insert into studentinfo (roll_no, name, address, age) values (357, 'Ber', '12th Floor', 18);
insert into studentinfo (roll_no, name, address, age) values (358, 'Lazarus', 'Suite 35', 16);
insert into studentinfo (roll_no, name, address, age) values (359, 'Christoph', 'Room 1179', 10);
insert into studentinfo (roll_no, name, address, age) values (360, 'Brewer', 'Room 436', 10);
insert into studentinfo (roll_no, name, address, age) values (361, 'Drusie', '14th Floor', 12);
insert into studentinfo (roll_no, name, address, age) values (362, 'Fraser', 'Room 1915', 7);
insert into studentinfo (roll_no, name, address, age) values (363, 'Eda', '15th Floor', 11);
insert into studentinfo (roll_no, name, address, age) values (364, 'Patin', 'PO Box 2148', 18);
insert into studentinfo (roll_no, name, address, age) values (365, 'Sadie', '4th Floor', 15);
insert into studentinfo (roll_no, name, address, age) values (366, 'Marshall', 'Apt 1026', 23);
insert into studentinfo (roll_no, name, address, age) values (367, 'Allyson', 'Suite 80', 12);
insert into studentinfo (roll_no, name, address, age) values (368, 'Bliss', 'Room 1677', 12);
insert into studentinfo (roll_no, name, address, age) values (369, 'Rickert', 'Suite 28', 19);
insert into studentinfo (roll_no, name, address, age) values (370, 'Veronika', 'Room 702', 6);
insert into studentinfo (roll_no, name, address, age) values (371, 'Huntley', 'Apt 1287', 23);
insert into studentinfo (roll_no, name, address, age) values (372, 'Ag', 'Apt 1879', 8);
insert into studentinfo (roll_no, name, address, age) values (373, 'Kirk', '1st Floor', 8);
insert into studentinfo (roll_no, name, address, age) values (374, 'Waneta', 'Apt 310', 15);
insert into studentinfo (roll_no, name, address, age) values (375, 'Fayette', '9th Floor', 24);
insert into studentinfo (roll_no, name, address, age) values (376, 'Kacie', '1st Floor', 15);
insert into studentinfo (roll_no, name, address, age) values (377, 'Anderea', 'Room 899', 19);
insert into studentinfo (roll_no, name, address, age) values (378, 'Devina', 'Apt 1356', 12);
insert into studentinfo (roll_no, name, address, age) values (379, 'Noni', '19th Floor', 14);
insert into studentinfo (roll_no, name, address, age) values (380, 'Falito', 'PO Box 20009', 18);
insert into studentinfo (roll_no, name, address, age) values (381, 'Karon', 'Apt 831', 17);
insert into studentinfo (roll_no, name, address, age) values (382, 'Thomasin', '6th Floor', null);
insert into studentinfo (roll_no, name, address, age) values (383, 'Nichols', 'Room 909', 12);
insert into studentinfo (roll_no, name, address, age) values (384, 'Mina', 'Suite 47', 23);
insert into studentinfo (roll_no, name, address, age) values (385, 'Tasia', 'Suite 47', 6);
insert into studentinfo (roll_no, name, address, age) values (386, 'Novelia', 'Apt 1497', 9);
insert into studentinfo (roll_no, name, address, age) values (387, 'Laurie', '2nd Floor', 21);
insert into studentinfo (roll_no, name, address, age) values (388, 'Roselin', 'PO Box 84293', 16);
insert into studentinfo (roll_no, name, address, age) values (389, 'Krissie', 'Suite 44', 19);
insert into studentinfo (roll_no, name, address, age) values (390, 'Amy', '8th Floor', 9);
insert into studentinfo (roll_no, name, address, age) values (391, 'Willi', 'Room 1481', 9);
insert into studentinfo (roll_no, name, address, age) values (392, 'Saxon', 'PO Box 78425', 6);
insert into studentinfo (roll_no, name, address, age) values (393, 'Mallorie', 'PO Box 68635', 18);
insert into studentinfo (roll_no, name, address, age) values (394, 'Carleton', 'Suite 67', 24);
insert into studentinfo (roll_no, name, address, age) values (395, 'Constance', 'Room 630', 13);
insert into studentinfo (roll_no, name, address, age) values (396, 'Ursula', 'PO Box 43511', 14);
insert into studentinfo (roll_no, name, address, age) values (397, 'Faulkner', 'Room 1119', 8);
insert into studentinfo (roll_no, name, address, age) values (398, 'Mariejeanne', 'Suite 89', 12);
insert into studentinfo (roll_no, name, address, age) values (399, 'Mala', 'Apt 1161', 19);
insert into studentinfo (roll_no, name, address, age) values (400, 'Lindsey', 'Room 560', 11);
insert into studentinfo (roll_no, name, address, age) values (401, 'Peta', 'Room 679', 16);
insert into studentinfo (roll_no, name, address, age) values (402, 'Laetitia', 'Apt 1840', 23);
insert into studentinfo (roll_no, name, address, age) values (403, 'Rudy', '12th Floor', 18);
insert into studentinfo (roll_no, name, address, age) values (404, 'Currie', 'PO Box 41230', null);
insert into studentinfo (roll_no, name, address, age) values (405, 'Elissa', '11th Floor', 8);
insert into studentinfo (roll_no, name, address, age) values (406, 'Malina', '9th Floor', 8);
insert into studentinfo (roll_no, name, address, age) values (407, 'Doralyn', 'Suite 48', null);
insert into studentinfo (roll_no, name, address, age) values (408, 'Cal', 'Suite 31', 17);
insert into studentinfo (roll_no, name, address, age) values (409, 'Cordelia', '13th Floor', 19);
insert into studentinfo (roll_no, name, address, age) values (410, 'Modesty', '12th Floor', 11);
insert into studentinfo (roll_no, name, address, age) values (411, 'Elana', 'PO Box 38149', 15);
insert into studentinfo (roll_no, name, address, age) values (412, 'Laural', 'Room 1653', 12);
insert into studentinfo (roll_no, name, address, age) values (413, 'Lia', '9th Floor', 24);
insert into studentinfo (roll_no, name, address, age) values (414, 'Zandra', '14th Floor', 7);
insert into studentinfo (roll_no, name, address, age) values (415, 'Raphael', 'Apt 724', 7);
insert into studentinfo (roll_no, name, address, age) values (416, 'Blakeley', 'Apt 701', null);
insert into studentinfo (roll_no, name, address, age) values (417, 'Cherrita', 'Suite 64', 17);
insert into studentinfo (roll_no, name, address, age) values (418, 'Adel', 'Apt 107', 22);
insert into studentinfo (roll_no, name, address, age) values (419, 'Bonita', '15th Floor', 6);
insert into studentinfo (roll_no, name, address, age) values (420, 'Annabal', 'PO Box 36908', 15);
insert into studentinfo (roll_no, name, address, age) values (421, 'Ermengarde', 'Suite 48', 17);
insert into studentinfo (roll_no, name, address, age) values (422, 'Tandie', '11th Floor', 23);
insert into studentinfo (roll_no, name, address, age) values (423, 'Patrick', '19th Floor', 21);
insert into studentinfo (roll_no, name, address, age) values (424, 'Kile', 'Apt 781', 8);
insert into studentinfo (roll_no, name, address, age) values (425, 'Ruggiero', 'Suite 92', 16);
insert into studentinfo (roll_no, name, address, age) values (426, 'Derick', 'Apt 175', 15);
insert into studentinfo (roll_no, name, address, age) values (427, 'Uta', 'Suite 87', 11);
insert into studentinfo (roll_no, name, address, age) values (428, 'Stanley', 'PO Box 34936', 10);
insert into studentinfo (roll_no, name, address, age) values (429, 'Deanne', 'Suite 88', 23);
insert into studentinfo (roll_no, name, address, age) values (430, 'Roddie', 'PO Box 70984', 20);
insert into studentinfo (roll_no, name, address, age) values (431, 'Gizela', '3rd Floor', 15);
insert into studentinfo (roll_no, name, address, age) values (432, 'Mort', 'Suite 34', null);
insert into studentinfo (roll_no, name, address, age) values (433, 'Xenia', 'Suite 32', 14);
insert into studentinfo (roll_no, name, address, age) values (434, 'Howie', 'Room 1118', 9);
insert into studentinfo (roll_no, name, address, age) values (435, 'Vitia', 'Room 103', null);
insert into studentinfo (roll_no, name, address, age) values (436, 'Alvina', 'Room 476', 7);
insert into studentinfo (roll_no, name, address, age) values (437, 'Josias', 'Apt 1458', 6);
insert into studentinfo (roll_no, name, address, age) values (438, 'Jeffry', 'Room 286', 18);
insert into studentinfo (roll_no, name, address, age) values (439, 'Eleanora', 'Apt 1183', 12);
insert into studentinfo (roll_no, name, address, age) values (440, 'Quincy', 'PO Box 93543', 14);
insert into studentinfo (roll_no, name, address, age) values (441, 'Corbin', 'Apt 1465', 15);
insert into studentinfo (roll_no, name, address, age) values (442, 'Odette', '15th Floor', null);
insert into studentinfo (roll_no, name, address, age) values (443, 'Gayelord', 'PO Box 33553', 24);
insert into studentinfo (roll_no, name, address, age) values (444, 'Tybie', 'Room 364', 16);
insert into studentinfo (roll_no, name, address, age) values (445, 'Tommi', 'Suite 40', 9);
insert into studentinfo (roll_no, name, address, age) values (446, 'Sullivan', 'Room 452', 24);
insert into studentinfo (roll_no, name, address, age) values (447, 'Eadith', '3rd Floor', 10);
insert into studentinfo (roll_no, name, address, age) values (448, 'Blythe', 'Apt 146', 15);
insert into studentinfo (roll_no, name, address, age) values (449, 'Jacquelyn', 'PO Box 84428', null);
insert into studentinfo (roll_no, name, address, age) values (450, 'Oliy', 'Suite 21', 22);
insert into studentinfo (roll_no, name, address, age) values (451, 'Nata', 'PO Box 40463', 22);
insert into studentinfo (roll_no, name, address, age) values (452, 'Bobby', 'PO Box 16939', 14);
insert into studentinfo (roll_no, name, address, age) values (453, 'Cristy', 'Suite 55', 12);
insert into studentinfo (roll_no, name, address, age) values (454, 'Joyce', 'Apt 1964', 20);
insert into studentinfo (roll_no, name, address, age) values (455, 'Sibylla', '20th Floor', 11);
insert into studentinfo (roll_no, name, address, age) values (456, 'Burlie', 'Suite 12', 7);
insert into studentinfo (roll_no, name, address, age) values (457, 'Gael', '1st Floor', 17);
insert into studentinfo (roll_no, name, address, age) values (458, 'Elisabeth', 'Room 164', 20);
insert into studentinfo (roll_no, name, address, age) values (459, 'Jacinta', 'Apt 1503', 22);
insert into studentinfo (roll_no, name, address, age) values (460, 'Doy', 'Room 262', 17);
insert into studentinfo (roll_no, name, address, age) values (461, 'Millard', 'PO Box 14500', 23);
insert into studentinfo (roll_no, name, address, age) values (462, 'Joelle', 'Room 926', 24);
insert into studentinfo (roll_no, name, address, age) values (463, 'Agace', '16th Floor', 16);
insert into studentinfo (roll_no, name, address, age) values (464, 'Nessie', 'Suite 41', 16);
insert into studentinfo (roll_no, name, address, age) values (465, 'Eba', 'Apt 1591', 7);
insert into studentinfo (roll_no, name, address, age) values (466, 'Dasi', 'Apt 830', 22);
insert into studentinfo (roll_no, name, address, age) values (467, 'Britta', 'Room 192', 20);
insert into studentinfo (roll_no, name, address, age) values (468, 'Shellie', 'Room 840', 18);
insert into studentinfo (roll_no, name, address, age) values (469, 'Yul', 'Apt 1147', 14);
insert into studentinfo (roll_no, name, address, age) values (470, 'Sig', '1st Floor', 9);
insert into studentinfo (roll_no, name, address, age) values (471, 'Berthe', 'Room 1423', 15);
insert into studentinfo (roll_no, name, address, age) values (472, 'Clifford', 'Suite 31', 13);
insert into studentinfo (roll_no, name, address, age) values (473, 'Maxie', 'Room 1905', 8);
insert into studentinfo (roll_no, name, address, age) values (474, 'Alisander', 'Room 388', 16);
insert into studentinfo (roll_no, name, address, age) values (475, 'Thayne', 'Suite 91', 6);
insert into studentinfo (roll_no, name, address, age) values (476, 'Burke', '12th Floor', 24);
insert into studentinfo (roll_no, name, address, age) values (477, 'Rani', 'Apt 567', 7);
insert into studentinfo (roll_no, name, address, age) values (478, 'Glen', 'Suite 24', null);
insert into studentinfo (roll_no, name, address, age) values (479, 'Claire', 'PO Box 59329', 20);
insert into studentinfo (roll_no, name, address, age) values (480, 'Godfry', 'Room 313', 14);
insert into studentinfo (roll_no, name, address, age) values (481, 'Benedict', '20th Floor', 15);
insert into studentinfo (roll_no, name, address, age) values (482, 'Flinn', 'PO Box 39767', 22);
insert into studentinfo (roll_no, name, address, age) values (483, 'Claus', '2nd Floor', 8);
insert into studentinfo (roll_no, name, address, age) values (484, 'Tamar', '16th Floor', 18);
insert into studentinfo (roll_no, name, address, age) values (485, 'Kit', 'PO Box 25408', null);
insert into studentinfo (roll_no, name, address, age) values (486, 'Ellynn', 'Apt 13', 20);
insert into studentinfo (roll_no, name, address, age) values (487, 'Ray', 'PO Box 20457', null);
insert into studentinfo (roll_no, name, address, age) values (488, 'Emeline', 'Suite 55', 6);
insert into studentinfo (roll_no, name, address, age) values (489, 'Tony', 'Apt 1090', 18);
insert into studentinfo (roll_no, name, address, age) values (490, 'Merrie', 'PO Box 4392', 23);
insert into studentinfo (roll_no, name, address, age) values (491, 'Maggi', 'Suite 69', 15);
insert into studentinfo (roll_no, name, address, age) values (492, 'Nedda', '19th Floor', 7);
insert into studentinfo (roll_no, name, address, age) values (493, 'Markos', 'Room 229', 20);
insert into studentinfo (roll_no, name, address, age) values (494, 'Catarina', '7th Floor', 22);
insert into studentinfo (roll_no, name, address, age) values (495, 'Gracia', 'PO Box 34508', 15);
insert into studentinfo (roll_no, name, address, age) values (496, 'Benedikt', '16th Floor', 12);
insert into studentinfo (roll_no, name, address, age) values (497, 'Tawnya', 'PO Box 16350', 17);
insert into studentinfo (roll_no, name, address, age) values (498, 'Ludwig', 'PO Box 93350', 20);
insert into studentinfo (roll_no, name, address, age) values (499, 'Wendel', 'Apt 1348', 10);
insert into studentinfo (roll_no, name, address, age) values (500, 'Packston', '3rd Floor', 17);
insert into studentinfo (roll_no, name, address, age) values (501, 'Gris', 'PO Box 42203', 19);
insert into studentinfo (roll_no, name, address, age) values (502, 'Amberly', 'Room 567', 24);
insert into studentinfo (roll_no, name, address, age) values (503, 'Raquel', 'Apt 497', null);
insert into studentinfo (roll_no, name, address, age) values (504, 'Kimmy', 'Room 1385', 18);
insert into studentinfo (roll_no, name, address, age) values (505, 'Carlie', '11th Floor', 15);
insert into studentinfo (roll_no, name, address, age) values (506, 'Earlie', 'Room 306', 14);
insert into studentinfo (roll_no, name, address, age) values (507, 'Janenna', 'PO Box 96520', 18);
insert into studentinfo (roll_no, name, address, age) values (508, 'Garrott', 'Suite 74', null);
insert into studentinfo (roll_no, name, address, age) values (509, 'Julienne', 'Suite 92', 18);
insert into studentinfo (roll_no, name, address, age) values (510, 'Verge', 'PO Box 17918', 22);
insert into studentinfo (roll_no, name, address, age) values (511, 'Greta', 'PO Box 1592', 24);
insert into studentinfo (roll_no, name, address, age) values (512, 'Hyatt', '9th Floor', 16);
insert into studentinfo (roll_no, name, address, age) values (513, 'Cos', 'Room 845', 14);
insert into studentinfo (roll_no, name, address, age) values (514, 'Linea', 'Suite 90', 22);
insert into studentinfo (roll_no, name, address, age) values (515, 'Yettie', 'Apt 1767', 8);
insert into studentinfo (roll_no, name, address, age) values (516, 'Freida', 'Apt 652', 6);
insert into studentinfo (roll_no, name, address, age) values (517, 'Annissa', 'Apt 1510', 6);
insert into studentinfo (roll_no, name, address, age) values (518, 'Marlane', 'PO Box 97475', 12);
insert into studentinfo (roll_no, name, address, age) values (519, 'Gerik', 'Suite 82', 19);
insert into studentinfo (roll_no, name, address, age) values (520, 'Sullivan', 'Suite 17', 13);
insert into studentinfo (roll_no, name, address, age) values (521, 'Elwira', 'Room 1862', 8);
insert into studentinfo (roll_no, name, address, age) values (522, 'Roseanna', 'Room 573', null);
insert into studentinfo (roll_no, name, address, age) values (523, 'Andee', 'Apt 42', 17);
insert into studentinfo (roll_no, name, address, age) values (524, 'Spence', 'Room 125', 23);
insert into studentinfo (roll_no, name, address, age) values (525, 'Carlota', 'Apt 266', 19);
insert into studentinfo (roll_no, name, address, age) values (526, 'Kirby', 'Apt 745', 14);
insert into studentinfo (roll_no, name, address, age) values (527, 'Maribel', 'Suite 20', 17);
insert into studentinfo (roll_no, name, address, age) values (528, 'Zebulen', '16th Floor', 12);
insert into studentinfo (roll_no, name, address, age) values (529, 'Gerri', 'Suite 12', 23);
insert into studentinfo (roll_no, name, address, age) values (530, 'Joice', 'PO Box 95430', 24);
insert into studentinfo (roll_no, name, address, age) values (531, 'Salomi', 'Suite 64', 22);
insert into studentinfo (roll_no, name, address, age) values (532, 'Austin', 'Room 27', 6);
insert into studentinfo (roll_no, name, address, age) values (533, 'Jillie', 'Apt 1191', 21);
insert into studentinfo (roll_no, name, address, age) values (534, 'De witt', 'Room 1704', 15);
insert into studentinfo (roll_no, name, address, age) values (535, 'Madelle', 'Apt 898', null);
insert into studentinfo (roll_no, name, address, age) values (536, 'Berni', 'PO Box 16205', 15);
insert into studentinfo (roll_no, name, address, age) values (537, 'Linea', 'Suite 55', 21);
insert into studentinfo (roll_no, name, address, age) values (538, 'Juliann', 'Room 1366', 17);
insert into studentinfo (roll_no, name, address, age) values (539, 'Deonne', 'Suite 51', 19);
insert into studentinfo (roll_no, name, address, age) values (540, 'Mae', 'Suite 13', 22);
insert into studentinfo (roll_no, name, address, age) values (541, 'Cletis', 'Suite 100', 20);
insert into studentinfo (roll_no, name, address, age) values (542, 'Matelda', 'PO Box 80182', 21);
insert into studentinfo (roll_no, name, address, age) values (543, 'Margalit', 'Room 1044', 14);
insert into studentinfo (roll_no, name, address, age) values (544, 'Cari', 'Suite 31', 18);
insert into studentinfo (roll_no, name, address, age) values (545, 'Julius', 'Room 1860', 8);
insert into studentinfo (roll_no, name, address, age) values (546, 'Maurice', 'Room 1310', 14);
insert into studentinfo (roll_no, name, address, age) values (547, 'Terza', 'Apt 614', 13);
insert into studentinfo (roll_no, name, address, age) values (548, 'Donny', 'Suite 20', 18);
insert into studentinfo (roll_no, name, address, age) values (549, 'Kaila', 'Room 868', 14);
insert into studentinfo (roll_no, name, address, age) values (550, 'Murielle', '7th Floor', 11);
insert into studentinfo (roll_no, name, address, age) values (551, 'Shara', 'Room 449', 21);
insert into studentinfo (roll_no, name, address, age) values (552, 'Darnell', 'Suite 21', 20);
insert into studentinfo (roll_no, name, address, age) values (553, 'Peadar', 'Suite 4', 24);
insert into studentinfo (roll_no, name, address, age) values (554, 'Gisella', 'Suite 55', 16);
insert into studentinfo (roll_no, name, address, age) values (555, 'Jamey', 'Apt 1027', 11);
insert into studentinfo (roll_no, name, address, age) values (556, 'Storm', 'Suite 40', null);
insert into studentinfo (roll_no, name, address, age) values (557, 'Krissy', 'Room 1587', 23);
insert into studentinfo (roll_no, name, address, age) values (558, 'Arnaldo', 'Apt 197', 19);
insert into studentinfo (roll_no, name, address, age) values (559, 'Sunny', 'Suite 93', 18);
insert into studentinfo (roll_no, name, address, age) values (560, 'David', '13th Floor', 11);
insert into studentinfo (roll_no, name, address, age) values (561, 'Shurlocke', 'Room 1075', 19);
insert into studentinfo (roll_no, name, address, age) values (562, 'Abramo', 'Room 1072', 23);
insert into studentinfo (roll_no, name, address, age) values (563, 'Karim', '16th Floor', 19);
insert into studentinfo (roll_no, name, address, age) values (564, 'Hedda', '18th Floor', 15);
insert into studentinfo (roll_no, name, address, age) values (565, 'Maure', 'PO Box 20634', 19);
insert into studentinfo (roll_no, name, address, age) values (566, 'Greer', '10th Floor', 18);
insert into studentinfo (roll_no, name, address, age) values (567, 'Skylar', 'Room 512', null);
insert into studentinfo (roll_no, name, address, age) values (568, 'Dolli', 'PO Box 3944', null);
insert into studentinfo (roll_no, name, address, age) values (569, 'Kristyn', '17th Floor', 23);
insert into studentinfo (roll_no, name, address, age) values (570, 'Jennilee', 'PO Box 63504', 23);
insert into studentinfo (roll_no, name, address, age) values (571, 'Daffie', 'Apt 216', 18);
insert into studentinfo (roll_no, name, address, age) values (572, 'Cosimo', 'Room 1133', 11);
insert into studentinfo (roll_no, name, address, age) values (573, 'Misha', 'Apt 1736', null);
insert into studentinfo (roll_no, name, address, age) values (574, 'Carree', '3rd Floor', 14);
insert into studentinfo (roll_no, name, address, age) values (575, 'Maryjo', 'Apt 1701', 19);
insert into studentinfo (roll_no, name, address, age) values (576, 'Stanley', 'Suite 30', 21);
insert into studentinfo (roll_no, name, address, age) values (577, 'Wolf', '10th Floor', 12);
insert into studentinfo (roll_no, name, address, age) values (578, 'Zacherie', 'Apt 1010', 16);
insert into studentinfo (roll_no, name, address, age) values (579, 'Henryetta', 'Suite 23', 13);
insert into studentinfo (roll_no, name, address, age) values (580, 'Adeline', 'PO Box 22792', 13);
insert into studentinfo (roll_no, name, address, age) values (581, 'Bailey', '17th Floor', 11);
insert into studentinfo (roll_no, name, address, age) values (582, 'Conrad', 'Apt 594', 16);
insert into studentinfo (roll_no, name, address, age) values (583, 'Yevette', 'Suite 53', 13);
insert into studentinfo (roll_no, name, address, age) values (584, 'Michelle', 'PO Box 13475', 7);
insert into studentinfo (roll_no, name, address, age) values (585, 'Raffarty', 'Apt 935', null);
insert into studentinfo (roll_no, name, address, age) values (586, 'Armand', '12th Floor', 8);
insert into studentinfo (roll_no, name, address, age) values (587, 'Halsy', 'Apt 967', 23);
insert into studentinfo (roll_no, name, address, age) values (588, 'Shandra', 'Apt 890', 23);
insert into studentinfo (roll_no, name, address, age) values (589, 'Chev', '10th Floor', null);
insert into studentinfo (roll_no, name, address, age) values (590, 'Kaycee', 'Apt 1102', 18);
insert into studentinfo (roll_no, name, address, age) values (591, 'Lesli', '8th Floor', 13);
insert into studentinfo (roll_no, name, address, age) values (592, 'Antoinette', 'Room 139', 6);
insert into studentinfo (roll_no, name, address, age) values (593, 'Jock', 'Room 1758', 16);
insert into studentinfo (roll_no, name, address, age) values (594, 'Thibaud', 'Apt 1407', null);
insert into studentinfo (roll_no, name, address, age) values (595, 'Nanine', '19th Floor', 9);
insert into studentinfo (roll_no, name, address, age) values (596, 'Toby', 'Room 1665', null);
insert into studentinfo (roll_no, name, address, age) values (597, 'Umeko', 'Room 809', null);
insert into studentinfo (roll_no, name, address, age) values (598, 'Jobi', '5th Floor', 15);
insert into studentinfo (roll_no, name, address, age) values (599, 'Elmo', 'PO Box 30947', 22);
insert into studentinfo (roll_no, name, address, age) values (600, 'Israel', 'Room 876', 24);
insert into studentinfo (roll_no, name, address, age) values (601, 'Jordanna', '13th Floor', 17);
insert into studentinfo (roll_no, name, address, age) values (602, 'Antonetta', '5th Floor', 12);
insert into studentinfo (roll_no, name, address, age) values (603, 'Honor', 'Suite 79', 9);
insert into studentinfo (roll_no, name, address, age) values (604, 'Freeland', 'Apt 1583', 13);
insert into studentinfo (roll_no, name, address, age) values (605, 'Raleigh', 'Room 1846', 23);
insert into studentinfo (roll_no, name, address, age) values (606, 'Rodrique', 'Apt 356', null);
insert into studentinfo (roll_no, name, address, age) values (607, 'Sonny', 'Suite 54', 16);
insert into studentinfo (roll_no, name, address, age) values (608, 'Trish', '20th Floor', 21);
insert into studentinfo (roll_no, name, address, age) values (609, 'Sigismond', '7th Floor', 18);
insert into studentinfo (roll_no, name, address, age) values (610, 'Boone', 'Apt 1280', null);
insert into studentinfo (roll_no, name, address, age) values (611, 'Star', 'Room 1073', 7);
insert into studentinfo (roll_no, name, address, age) values (612, 'Waylin', 'Room 1742', 23);
insert into studentinfo (roll_no, name, address, age) values (613, 'Cris', 'Suite 89', 10);
insert into studentinfo (roll_no, name, address, age) values (614, 'Moss', 'Apt 1523', 18);
insert into studentinfo (roll_no, name, address, age) values (615, 'Larine', 'Apt 1059', 21);
insert into studentinfo (roll_no, name, address, age) values (616, 'Willamina', 'Room 692', 19);
insert into studentinfo (roll_no, name, address, age) values (617, 'Karyl', 'Apt 526', 18);
insert into studentinfo (roll_no, name, address, age) values (618, 'Fredric', 'Room 404', 9);
insert into studentinfo (roll_no, name, address, age) values (619, 'Carly', 'Apt 1223', 16);
insert into studentinfo (roll_no, name, address, age) values (620, 'Garland', 'Suite 25', 15);
insert into studentinfo (roll_no, name, address, age) values (621, 'Millie', 'PO Box 85828', 16);
insert into studentinfo (roll_no, name, address, age) values (622, 'Dione', '1st Floor', 6);
insert into studentinfo (roll_no, name, address, age) values (623, 'Hulda', 'PO Box 3990', 12);
insert into studentinfo (roll_no, name, address, age) values (624, 'Rodrick', 'Room 527', 9);
insert into studentinfo (roll_no, name, address, age) values (625, 'Elfrida', 'Apt 187', 10);
insert into studentinfo (roll_no, name, address, age) values (626, 'Yardley', 'Room 1809', null);
insert into studentinfo (roll_no, name, address, age) values (627, 'Caldwell', 'PO Box 96114', 16);
insert into studentinfo (roll_no, name, address, age) values (628, 'Bird', 'Suite 63', 19);
insert into studentinfo (roll_no, name, address, age) values (629, 'Jennica', 'Suite 72', 16);
insert into studentinfo (roll_no, name, address, age) values (630, 'Reinhold', 'Room 939', 21);
insert into studentinfo (roll_no, name, address, age) values (631, 'Rosella', 'Room 1056', null);
insert into studentinfo (roll_no, name, address, age) values (632, 'Katharyn', 'PO Box 13373', 19);
insert into studentinfo (roll_no, name, address, age) values (633, 'Forester', 'Apt 129', null);
insert into studentinfo (roll_no, name, address, age) values (634, 'Alasteir', 'Room 1161', 24);
insert into studentinfo (roll_no, name, address, age) values (635, 'Nealson', 'PO Box 41282', 14);
insert into studentinfo (roll_no, name, address, age) values (636, 'Corty', 'Apt 1962', 21);
insert into studentinfo (roll_no, name, address, age) values (637, 'Maggie', 'Room 1193', 12);
insert into studentinfo (roll_no, name, address, age) values (638, 'Thatch', 'PO Box 98329', 20);
insert into studentinfo (roll_no, name, address, age) values (639, 'Borden', 'Apt 1723', 11);
insert into studentinfo (roll_no, name, address, age) values (640, 'Weylin', 'PO Box 25571', 24);
insert into studentinfo (roll_no, name, address, age) values (641, 'Page', '4th Floor', 18);
insert into studentinfo (roll_no, name, address, age) values (642, 'Avis', 'Apt 530', 12);
insert into studentinfo (roll_no, name, address, age) values (643, 'Clareta', 'Room 1123', 12);
insert into studentinfo (roll_no, name, address, age) values (644, 'Emmy', 'Suite 38', 13);
insert into studentinfo (roll_no, name, address, age) values (645, 'Rodrick', 'Room 1007', 13);
insert into studentinfo (roll_no, name, address, age) values (646, 'Basilio', 'Room 1654', 12);
insert into studentinfo (roll_no, name, address, age) values (647, 'Austen', 'Room 439', 17);
insert into studentinfo (roll_no, name, address, age) values (648, 'Nydia', 'Apt 1880', 8);
insert into studentinfo (roll_no, name, address, age) values (649, 'Cornie', 'Suite 90', 11);
insert into studentinfo (roll_no, name, address, age) values (650, 'Amara', 'Apt 1671', 24);
insert into studentinfo (roll_no, name, address, age) values (651, 'Inigo', 'Suite 7', 24);
insert into studentinfo (roll_no, name, address, age) values (652, 'Rafferty', 'PO Box 248', null);
insert into studentinfo (roll_no, name, address, age) values (653, 'Deeann', 'Suite 55', 12);
insert into studentinfo (roll_no, name, address, age) values (654, 'Natalya', 'Suite 76', 13);
insert into studentinfo (roll_no, name, address, age) values (655, 'Annabela', 'Room 366', 20);
insert into studentinfo (roll_no, name, address, age) values (656, 'Annelise', 'Room 797', 23);
insert into studentinfo (roll_no, name, address, age) values (657, 'Tabbi', '13th Floor', 9);
insert into studentinfo (roll_no, name, address, age) values (658, 'Chick', 'Apt 840', 15);
insert into studentinfo (roll_no, name, address, age) values (659, 'Germaine', '18th Floor', 20);
insert into studentinfo (roll_no, name, address, age) values (660, 'Maura', 'PO Box 27934', 10);
insert into studentinfo (roll_no, name, address, age) values (661, 'Rourke', 'Room 20', 12);
insert into studentinfo (roll_no, name, address, age) values (662, 'Julita', 'Room 1432', 13);
insert into studentinfo (roll_no, name, address, age) values (663, 'Cory', 'PO Box 758', 7);
insert into studentinfo (roll_no, name, address, age) values (664, 'Adella', 'Suite 14', 21);
insert into studentinfo (roll_no, name, address, age) values (665, 'Trisha', 'PO Box 99225', 10);
insert into studentinfo (roll_no, name, address, age) values (666, 'Timothea', 'Apt 1596', null);
insert into studentinfo (roll_no, name, address, age) values (667, 'Jacobo', '1st Floor', 7);
insert into studentinfo (roll_no, name, address, age) values (668, 'Tess', 'Room 1309', 12);
insert into studentinfo (roll_no, name, address, age) values (669, 'Rachel', 'Apt 163', 6);
insert into studentinfo (roll_no, name, address, age) values (670, 'Katuscha', 'Apt 1809', 14);
insert into studentinfo (roll_no, name, address, age) values (671, 'Eydie', 'Suite 45', 11);
insert into studentinfo (roll_no, name, address, age) values (672, 'Ingelbert', 'Room 786', 22);
insert into studentinfo (roll_no, name, address, age) values (673, 'Lewie', 'Room 1181', 19);
insert into studentinfo (roll_no, name, address, age) values (674, 'Sylvia', '5th Floor', 13);
insert into studentinfo (roll_no, name, address, age) values (675, 'Darwin', 'Apt 1240', 12);
insert into studentinfo (roll_no, name, address, age) values (676, 'Ada', '12th Floor', 22);
insert into studentinfo (roll_no, name, address, age) values (677, 'Armando', 'Apt 1005', 8);
insert into studentinfo (roll_no, name, address, age) values (678, 'Natasha', 'Suite 20', 15);
insert into studentinfo (roll_no, name, address, age) values (679, 'Ludvig', 'Room 1984', 21);
insert into studentinfo (roll_no, name, address, age) values (680, 'Heall', 'Room 229', 11);
insert into studentinfo (roll_no, name, address, age) values (681, 'Kordula', 'Room 300', 15);
insert into studentinfo (roll_no, name, address, age) values (682, 'Phil', '17th Floor', null);
insert into studentinfo (roll_no, name, address, age) values (683, 'Mycah', 'Suite 45', 22);
insert into studentinfo (roll_no, name, address, age) values (684, 'Ryann', 'PO Box 24471', 6);
insert into studentinfo (roll_no, name, address, age) values (685, 'Barris', '20th Floor', 8);
insert into studentinfo (roll_no, name, address, age) values (686, 'Charil', 'Apt 855', 16);
insert into studentinfo (roll_no, name, address, age) values (687, 'Estell', 'Room 161', 17);
insert into studentinfo (roll_no, name, address, age) values (688, 'Corissa', 'Apt 594', 6);
insert into studentinfo (roll_no, name, address, age) values (689, 'Emmey', 'Suite 26', 9);
insert into studentinfo (roll_no, name, address, age) values (690, 'Bunni', 'Room 241', 7);
insert into studentinfo (roll_no, name, address, age) values (691, 'Darn', 'Room 177', 13);
insert into studentinfo (roll_no, name, address, age) values (692, 'Rosmunda', 'Suite 2', 11);
insert into studentinfo (roll_no, name, address, age) values (693, 'Glenda', 'Suite 56', 21);
insert into studentinfo (roll_no, name, address, age) values (694, 'Bondon', 'PO Box 46124', null);
insert into studentinfo (roll_no, name, address, age) values (695, 'Delbert', 'PO Box 94654', 10);
insert into studentinfo (roll_no, name, address, age) values (696, 'Jone', 'Suite 36', 13);
insert into studentinfo (roll_no, name, address, age) values (697, 'Warren', '3rd Floor', 16);
insert into studentinfo (roll_no, name, address, age) values (698, 'Jinny', '11th Floor', 15);
insert into studentinfo (roll_no, name, address, age) values (699, 'Fulton', 'Apt 668', 18);
insert into studentinfo (roll_no, name, address, age) values (700, 'Burl', 'Apt 666', 22);
insert into studentinfo (roll_no, name, address, age) values (701, 'Franni', '2nd Floor', 12);
insert into studentinfo (roll_no, name, address, age) values (702, 'Allister', 'Suite 14', 14);
insert into studentinfo (roll_no, name, address, age) values (703, 'Hubey', 'PO Box 99854', 23);
insert into studentinfo (roll_no, name, address, age) values (704, 'Marchelle', 'Room 1615', 8);
insert into studentinfo (roll_no, name, address, age) values (705, 'Shelden', 'PO Box 13860', 17);
insert into studentinfo (roll_no, name, address, age) values (706, 'Guinna', '15th Floor', 6);
insert into studentinfo (roll_no, name, address, age) values (707, 'Jo-ann', 'Room 1991', 10);
insert into studentinfo (roll_no, name, address, age) values (708, 'Janek', 'Apt 1799', 8);
insert into studentinfo (roll_no, name, address, age) values (709, 'Clyde', 'Room 1686', 10);
insert into studentinfo (roll_no, name, address, age) values (710, 'Magdalen', 'Room 1650', 11);
insert into studentinfo (roll_no, name, address, age) values (711, 'Adolphe', 'PO Box 91837', 15);
insert into studentinfo (roll_no, name, address, age) values (712, 'Nikolaos', '10th Floor', null);
insert into studentinfo (roll_no, name, address, age) values (713, 'Jerrie', '4th Floor', null);
insert into studentinfo (roll_no, name, address, age) values (714, 'Deana', '20th Floor', 19);
insert into studentinfo (roll_no, name, address, age) values (715, 'Lorry', 'Apt 693', 22);
insert into studentinfo (roll_no, name, address, age) values (716, 'Benedikta', 'Suite 97', 19);
insert into studentinfo (roll_no, name, address, age) values (717, 'Deck', 'PO Box 22586', 9);
insert into studentinfo (roll_no, name, address, age) values (718, 'Elias', '16th Floor', 12);
insert into studentinfo (roll_no, name, address, age) values (719, 'Paco', '9th Floor', 22);
insert into studentinfo (roll_no, name, address, age) values (720, 'Orlan', '10th Floor', null);
insert into studentinfo (roll_no, name, address, age) values (721, 'Stormie', 'Apt 402', 13);
insert into studentinfo (roll_no, name, address, age) values (722, 'Maryrose', 'Room 571', 19);
insert into studentinfo (roll_no, name, address, age) values (723, 'Rodd', 'Apt 1307', 10);
insert into studentinfo (roll_no, name, address, age) values (724, 'Conrad', 'Apt 1368', 11);
insert into studentinfo (roll_no, name, address, age) values (725, 'Kahaleel', 'Suite 99', null);
insert into studentinfo (roll_no, name, address, age) values (726, 'Davidson', 'PO Box 19663', 14);
insert into studentinfo (roll_no, name, address, age) values (727, 'Bryce', 'Suite 32', 21);
insert into studentinfo (roll_no, name, address, age) values (728, 'Ive', 'Apt 748', 13);
insert into studentinfo (roll_no, name, address, age) values (729, 'Ellsworth', 'Suite 33', 22);
insert into studentinfo (roll_no, name, address, age) values (730, 'Diego', 'Room 76', 6);
insert into studentinfo (roll_no, name, address, age) values (731, 'Car', 'Suite 100', 14);
insert into studentinfo (roll_no, name, address, age) values (732, 'Dorise', 'Apt 1526', 7);
insert into studentinfo (roll_no, name, address, age) values (733, 'Marc', 'Apt 446', null);
insert into studentinfo (roll_no, name, address, age) values (734, 'Danice', 'Suite 18', 16);
insert into studentinfo (roll_no, name, address, age) values (735, 'Rosalinda', 'Suite 17', 20);
insert into studentinfo (roll_no, name, address, age) values (736, 'Garrott', '20th Floor', 10);
insert into studentinfo (roll_no, name, address, age) values (737, 'Leif', 'Room 503', 16);
insert into studentinfo (roll_no, name, address, age) values (738, 'Joannes', 'Room 353', 14);
insert into studentinfo (roll_no, name, address, age) values (739, 'Wallace', 'Suite 45', 11);
insert into studentinfo (roll_no, name, address, age) values (740, 'Kristien', 'Apt 682', 23);
insert into studentinfo (roll_no, name, address, age) values (741, 'Brigitta', 'Room 898', 21);
insert into studentinfo (roll_no, name, address, age) values (742, 'Tammie', '9th Floor', null);
insert into studentinfo (roll_no, name, address, age) values (743, 'Herc', 'Suite 40', 10);
insert into studentinfo (roll_no, name, address, age) values (744, 'Gerri', 'Room 1779', 24);
insert into studentinfo (roll_no, name, address, age) values (745, 'Persis', 'Apt 416', 23);
insert into studentinfo (roll_no, name, address, age) values (746, 'Merlina', 'Room 647', 15);
insert into studentinfo (roll_no, name, address, age) values (747, 'Dominique', 'Room 1208', 14);
insert into studentinfo (roll_no, name, address, age) values (748, 'Deloris', 'Suite 41', 14);
insert into studentinfo (roll_no, name, address, age) values (749, 'Rory', '3rd Floor', 21);
insert into studentinfo (roll_no, name, address, age) values (750, 'Suzy', '4th Floor', 8);
insert into studentinfo (roll_no, name, address, age) values (751, 'Erich', 'Suite 97', 11);
insert into studentinfo (roll_no, name, address, age) values (752, 'Ermengarde', '7th Floor', 15);
insert into studentinfo (roll_no, name, address, age) values (753, 'Colver', '2nd Floor', 13);
insert into studentinfo (roll_no, name, address, age) values (754, 'Alyce', 'PO Box 79436', 21);
insert into studentinfo (roll_no, name, address, age) values (755, 'Normand', 'Apt 1475', 14);
insert into studentinfo (roll_no, name, address, age) values (756, 'Brooke', 'Suite 93', 15);
insert into studentinfo (roll_no, name, address, age) values (757, 'Rolfe', 'Suite 43', 24);
insert into studentinfo (roll_no, name, address, age) values (758, 'Daffy', 'Apt 359', 14);
insert into studentinfo (roll_no, name, address, age) values (759, 'Werner', '10th Floor', null);
insert into studentinfo (roll_no, name, address, age) values (760, 'Lock', 'Room 1913', 19);
insert into studentinfo (roll_no, name, address, age) values (761, 'Reinhold', 'Room 1401', 17);
insert into studentinfo (roll_no, name, address, age) values (762, 'Nerti', 'Apt 1970', 19);
insert into studentinfo (roll_no, name, address, age) values (763, 'Fraser', 'Suite 98', 10);
insert into studentinfo (roll_no, name, address, age) values (764, 'Agnese', '8th Floor', 6);
insert into studentinfo (roll_no, name, address, age) values (765, 'Gil', 'Suite 73', 13);
insert into studentinfo (roll_no, name, address, age) values (766, 'Lulita', '18th Floor', 20);
insert into studentinfo (roll_no, name, address, age) values (767, 'Viole', 'PO Box 21453', 18);
insert into studentinfo (roll_no, name, address, age) values (768, 'Abel', '3rd Floor', 10);
insert into studentinfo (roll_no, name, address, age) values (769, 'Maria', '9th Floor', 15);
insert into studentinfo (roll_no, name, address, age) values (770, 'Stacee', 'Room 1188', 22);
insert into studentinfo (roll_no, name, address, age) values (771, 'Gabriel', 'PO Box 95711', 23);
insert into studentinfo (roll_no, name, address, age) values (772, 'Gavin', 'PO Box 47388', 17);
insert into studentinfo (roll_no, name, address, age) values (773, 'Osmond', '8th Floor', 18);
insert into studentinfo (roll_no, name, address, age) values (774, 'Barbabas', 'Suite 5', 22);
insert into studentinfo (roll_no, name, address, age) values (775, 'Rayna', '11th Floor', 11);
insert into studentinfo (roll_no, name, address, age) values (776, 'Mureil', 'PO Box 10720', null);
insert into studentinfo (roll_no, name, address, age) values (777, 'Wenda', '16th Floor', 8);
insert into studentinfo (roll_no, name, address, age) values (778, 'Andres', '7th Floor', 11);
insert into studentinfo (roll_no, name, address, age) values (779, 'Nelle', 'Apt 1134', 8);
insert into studentinfo (roll_no, name, address, age) values (780, 'Mic', 'Suite 68', null);
insert into studentinfo (roll_no, name, address, age) values (781, 'Olva', 'Room 81', 10);
insert into studentinfo (roll_no, name, address, age) values (782, 'Padgett', 'Suite 11', 8);
insert into studentinfo (roll_no, name, address, age) values (783, 'Cookie', 'Suite 51', null);
insert into studentinfo (roll_no, name, address, age) values (784, 'Ollie', 'Suite 61', 7);
insert into studentinfo (roll_no, name, address, age) values (785, 'Leone', 'Room 306', 11);
insert into studentinfo (roll_no, name, address, age) values (786, 'Tiffany', 'PO Box 13007', 17);
insert into studentinfo (roll_no, name, address, age) values (787, 'Berke', 'PO Box 89959', 20);
insert into studentinfo (roll_no, name, address, age) values (788, 'Remy', 'PO Box 16961', 19);
insert into studentinfo (roll_no, name, address, age) values (789, 'Faustina', 'PO Box 81580', 9);
insert into studentinfo (roll_no, name, address, age) values (790, 'Kass', 'Room 1596', 20);
insert into studentinfo (roll_no, name, address, age) values (791, 'Barby', '20th Floor', 18);
insert into studentinfo (roll_no, name, address, age) values (792, 'Jeramie', 'Apt 1370', 22);
insert into studentinfo (roll_no, name, address, age) values (793, 'Lowell', '13th Floor', 10);
insert into studentinfo (roll_no, name, address, age) values (794, 'Agnese', 'Room 879', 18);
insert into studentinfo (roll_no, name, address, age) values (795, 'Elvina', '13th Floor', 12);
insert into studentinfo (roll_no, name, address, age) values (796, 'Caro', 'PO Box 15071', null);
insert into studentinfo (roll_no, name, address, age) values (797, 'Kirsteni', 'PO Box 44048', 21);
insert into studentinfo (roll_no, name, address, age) values (798, 'Sisely', 'Apt 1672', 9);
insert into studentinfo (roll_no, name, address, age) values (799, 'Moreen', 'Apt 1378', 9);
insert into studentinfo (roll_no, name, address, age) values (800, 'Emmit', 'Suite 53', 13);
insert into studentinfo (roll_no, name, address, age) values (801, 'Kelsey', '8th Floor', null);
insert into studentinfo (roll_no, name, address, age) values (802, 'Anet', '9th Floor', null);
insert into studentinfo (roll_no, name, address, age) values (803, 'Tracey', 'Room 552', 23);
insert into studentinfo (roll_no, name, address, age) values (804, 'Judas', 'Suite 100', 20);
insert into studentinfo (roll_no, name, address, age) values (805, 'Blakeley', 'Suite 73', 17);
insert into studentinfo (roll_no, name, address, age) values (806, 'Lian', '15th Floor', 13);
insert into studentinfo (roll_no, name, address, age) values (807, 'Ibrahim', '13th Floor', 10);
insert into studentinfo (roll_no, name, address, age) values (808, 'Eadie', 'Room 489', 10);
insert into studentinfo (roll_no, name, address, age) values (809, 'Duncan', 'Room 154', null);
insert into studentinfo (roll_no, name, address, age) values (810, 'Constantina', 'Room 554', 8);
insert into studentinfo (roll_no, name, address, age) values (811, 'Ambrosio', 'Suite 40', 19);
insert into studentinfo (roll_no, name, address, age) values (812, 'Cash', 'PO Box 34278', 24);
insert into studentinfo (roll_no, name, address, age) values (813, 'Lucian', 'Suite 2', 16);
insert into studentinfo (roll_no, name, address, age) values (814, 'Roana', 'Apt 1912', 23);
insert into studentinfo (roll_no, name, address, age) values (815, 'Pippo', 'Room 930', 16);
insert into studentinfo (roll_no, name, address, age) values (816, 'Koren', '10th Floor', 11);
insert into studentinfo (roll_no, name, address, age) values (817, 'Cameron', 'Room 705', 17);
insert into studentinfo (roll_no, name, address, age) values (818, 'Cullen', 'Apt 1819', 8);
insert into studentinfo (roll_no, name, address, age) values (819, 'Didi', 'Apt 1234', 7);
insert into studentinfo (roll_no, name, address, age) values (820, 'Catherine', 'Room 739', 8);
insert into studentinfo (roll_no, name, address, age) values (821, 'Gustavo', 'Room 997', 19);
insert into studentinfo (roll_no, name, address, age) values (822, 'Jamal', 'Apt 1001', 13);
insert into studentinfo (roll_no, name, address, age) values (823, 'Lek', 'Suite 72', 10);
insert into studentinfo (roll_no, name, address, age) values (824, 'Theodora', '8th Floor', 15);
insert into studentinfo (roll_no, name, address, age) values (825, 'Kala', 'PO Box 10914', 21);
insert into studentinfo (roll_no, name, address, age) values (826, 'Jorey', 'PO Box 72646', 14);
insert into studentinfo (roll_no, name, address, age) values (827, 'Coraline', '11th Floor', 11);
insert into studentinfo (roll_no, name, address, age) values (828, 'Clyde', 'PO Box 64281', 23);
insert into studentinfo (roll_no, name, address, age) values (829, 'Shelagh', 'Apt 653', 18);
insert into studentinfo (roll_no, name, address, age) values (830, 'Davina', 'Suite 53', 24);
insert into studentinfo (roll_no, name, address, age) values (831, 'Max', '17th Floor', 24);
insert into studentinfo (roll_no, name, address, age) values (832, 'Jackson', 'Apt 1045', 13);
insert into studentinfo (roll_no, name, address, age) values (833, 'Darelle', '14th Floor', 18);
insert into studentinfo (roll_no, name, address, age) values (834, 'Jayson', 'PO Box 65936', 8);
insert into studentinfo (roll_no, name, address, age) values (835, 'Maisey', 'Apt 600', 14);
insert into studentinfo (roll_no, name, address, age) values (836, 'Rodger', 'Room 1838', 13);
insert into studentinfo (roll_no, name, address, age) values (837, 'Ardelle', 'Apt 767', 20);
insert into studentinfo (roll_no, name, address, age) values (838, 'Reggy', '6th Floor', null);
insert into studentinfo (roll_no, name, address, age) values (839, 'Huntley', 'Room 1734', 24);
insert into studentinfo (roll_no, name, address, age) values (840, 'Nealy', 'Apt 463', 8);
insert into studentinfo (roll_no, name, address, age) values (841, 'Dennie', 'Apt 353', 10);
insert into studentinfo (roll_no, name, address, age) values (842, 'Jaquith', 'Room 1573', 13);
insert into studentinfo (roll_no, name, address, age) values (843, 'Sharyl', 'Room 862', 11);
insert into studentinfo (roll_no, name, address, age) values (844, 'Chase', '8th Floor', 21);
insert into studentinfo (roll_no, name, address, age) values (845, 'Amber', 'Room 627', 11);
insert into studentinfo (roll_no, name, address, age) values (846, 'Paulina', 'Room 1329', 18);
insert into studentinfo (roll_no, name, address, age) values (847, 'Dulciana', '10th Floor', 12);
insert into studentinfo (roll_no, name, address, age) values (848, 'Sarette', 'PO Box 71675', 13);
insert into studentinfo (roll_no, name, address, age) values (849, 'Cos', 'Room 655', 18);
insert into studentinfo (roll_no, name, address, age) values (850, 'Cyrille', 'Room 1969', 15);
insert into studentinfo (roll_no, name, address, age) values (851, 'Nicholas', 'Room 1468', 7);
insert into studentinfo (roll_no, name, address, age) values (852, 'Dorey', 'Apt 1553', 17);
insert into studentinfo (roll_no, name, address, age) values (853, 'Alden', 'PO Box 81029', 20);
insert into studentinfo (roll_no, name, address, age) values (854, 'Naomi', 'Suite 69', 16);
insert into studentinfo (roll_no, name, address, age) values (855, 'Alisun', 'Apt 600', 24);
insert into studentinfo (roll_no, name, address, age) values (856, 'Nedda', 'Room 236', 14);
insert into studentinfo (roll_no, name, address, age) values (857, 'Jesse', 'Suite 100', 9);
insert into studentinfo (roll_no, name, address, age) values (858, 'Alexi', 'PO Box 4161', 12);
insert into studentinfo (roll_no, name, address, age) values (859, 'Neda', 'Suite 14', 8);
insert into studentinfo (roll_no, name, address, age) values (860, 'Zondra', 'Suite 71', 6);
insert into studentinfo (roll_no, name, address, age) values (861, 'L;urette', 'Room 43', 15);
insert into studentinfo (roll_no, name, address, age) values (862, 'Jodie', 'Room 474', 19);
insert into studentinfo (roll_no, name, address, age) values (863, 'Faunie', '16th Floor', 15);
insert into studentinfo (roll_no, name, address, age) values (864, 'Susan', 'PO Box 471', 23);
insert into studentinfo (roll_no, name, address, age) values (865, 'Hunfredo', 'Apt 694', 10);
insert into studentinfo (roll_no, name, address, age) values (866, 'Johnnie', 'PO Box 47021', 7);
insert into studentinfo (roll_no, name, address, age) values (867, 'Marylou', 'Room 1020', 18);
insert into studentinfo (roll_no, name, address, age) values (868, 'Devy', 'Room 319', 22);
insert into studentinfo (roll_no, name, address, age) values (869, 'Angelina', 'Room 212', 15);
insert into studentinfo (roll_no, name, address, age) values (870, 'Jolie', 'Apt 1229', null);
insert into studentinfo (roll_no, name, address, age) values (871, 'Loydie', 'PO Box 98299', 16);
insert into studentinfo (roll_no, name, address, age) values (872, 'Sabina', 'Apt 161', 24);
insert into studentinfo (roll_no, name, address, age) values (873, 'Joletta', 'PO Box 54996', null);
insert into studentinfo (roll_no, name, address, age) values (874, 'Ameline', '2nd Floor', 6);
insert into studentinfo (roll_no, name, address, age) values (875, 'Jemmie', 'PO Box 77735', 9);
insert into studentinfo (roll_no, name, address, age) values (876, 'Beatrisa', 'Room 368', 14);
insert into studentinfo (roll_no, name, address, age) values (877, 'Arlee', 'Apt 2000', 6);
insert into studentinfo (roll_no, name, address, age) values (878, 'Rachelle', '2nd Floor', 19);
insert into studentinfo (roll_no, name, address, age) values (879, 'Lyn', 'Suite 83', 16);
insert into studentinfo (roll_no, name, address, age) values (880, 'Holli', '5th Floor', 10);
insert into studentinfo (roll_no, name, address, age) values (881, 'Quintus', 'Apt 1303', 22);
insert into studentinfo (roll_no, name, address, age) values (882, 'Tonie', 'PO Box 11906', 23);
insert into studentinfo (roll_no, name, address, age) values (883, 'Pandora', 'PO Box 43527', 14);
insert into studentinfo (roll_no, name, address, age) values (884, 'Edin', 'Suite 75', 23);
insert into studentinfo (roll_no, name, address, age) values (885, 'Juanita', 'Apt 1219', 13);
insert into studentinfo (roll_no, name, address, age) values (886, 'Lorine', '13th Floor', 9);
insert into studentinfo (roll_no, name, address, age) values (887, 'Adeline', 'PO Box 84249', 17);
insert into studentinfo (roll_no, name, address, age) values (888, 'Walden', 'Apt 1074', 23);
insert into studentinfo (roll_no, name, address, age) values (889, 'Waldon', 'Room 291', 19);
insert into studentinfo (roll_no, name, address, age) values (890, 'Timotheus', 'Apt 1038', null);
insert into studentinfo (roll_no, name, address, age) values (891, 'Cecilius', 'Suite 68', 18);
insert into studentinfo (roll_no, name, address, age) values (892, 'Ferdy', 'PO Box 21644', 21);
insert into studentinfo (roll_no, name, address, age) values (893, 'Arturo', '12th Floor', 14);
insert into studentinfo (roll_no, name, address, age) values (894, 'Lorry', 'Apt 89', 9);
insert into studentinfo (roll_no, name, address, age) values (895, 'Sarah', 'Suite 37', 11);
insert into studentinfo (roll_no, name, address, age) values (896, 'Gay', 'Suite 83', 17);
insert into studentinfo (roll_no, name, address, age) values (897, 'Donelle', 'Room 1827', 12);
insert into studentinfo (roll_no, name, address, age) values (898, 'Randie', '8th Floor', null);
insert into studentinfo (roll_no, name, address, age) values (899, 'Lyn', 'Room 1665', 14);
insert into studentinfo (roll_no, name, address, age) values (900, 'Samantha', 'Room 20', 19);
insert into studentinfo (roll_no, name, address, age) values (901, 'Donella', 'Room 868', 20);
insert into studentinfo (roll_no, name, address, age) values (902, 'Claus', 'PO Box 96034', 8);
insert into studentinfo (roll_no, name, address, age) values (903, 'Isabelita', 'Room 1534', 9);
insert into studentinfo (roll_no, name, address, age) values (904, 'Martha', 'Suite 11', 15);
insert into studentinfo (roll_no, name, address, age) values (905, 'Angelia', 'PO Box 29340', 6);
insert into studentinfo (roll_no, name, address, age) values (906, 'Hermie', 'Suite 1', 16);
insert into studentinfo (roll_no, name, address, age) values (907, 'Dennison', 'Suite 90', 10);
insert into studentinfo (roll_no, name, address, age) values (908, 'Brina', 'Room 2', null);
insert into studentinfo (roll_no, name, address, age) values (909, 'Aliza', '16th Floor', null);
insert into studentinfo (roll_no, name, address, age) values (910, 'Torrey', 'Room 384', 24);
insert into studentinfo (roll_no, name, address, age) values (911, 'Riordan', 'Suite 86', 10);
insert into studentinfo (roll_no, name, address, age) values (912, 'Darrelle', 'Apt 782', 8);
insert into studentinfo (roll_no, name, address, age) values (913, 'Zonnya', 'Suite 63', 9);
insert into studentinfo (roll_no, name, address, age) values (914, 'Ruthi', '8th Floor', 14);
insert into studentinfo (roll_no, name, address, age) values (915, 'Carolin', 'PO Box 73425', 17);
insert into studentinfo (roll_no, name, address, age) values (916, 'Flor', 'PO Box 46555', 21);
insert into studentinfo (roll_no, name, address, age) values (917, 'Filippo', 'PO Box 3099', 20);
insert into studentinfo (roll_no, name, address, age) values (918, 'Ibby', 'Suite 64', 11);
insert into studentinfo (roll_no, name, address, age) values (919, 'Hilly', 'PO Box 84877', 18);
insert into studentinfo (roll_no, name, address, age) values (920, 'Caron', 'PO Box 8242', 19);
insert into studentinfo (roll_no, name, address, age) values (921, 'Willie', 'PO Box 70273', null);
insert into studentinfo (roll_no, name, address, age) values (922, 'Baxy', 'PO Box 1480', 16);
insert into studentinfo (roll_no, name, address, age) values (923, 'Sheridan', 'Apt 719', 6);
insert into studentinfo (roll_no, name, address, age) values (924, 'Elsa', 'Apt 1931', 10);
insert into studentinfo (roll_no, name, address, age) values (925, 'David', 'Room 1010', 22);
insert into studentinfo (roll_no, name, address, age) values (926, 'Sanford', 'Room 783', 21);
insert into studentinfo (roll_no, name, address, age) values (927, 'Manolo', '14th Floor', 14);
insert into studentinfo (roll_no, name, address, age) values (928, 'Holly', 'Suite 96', 6);
insert into studentinfo (roll_no, name, address, age) values (929, 'Dorelle', 'Suite 92', 19);
insert into studentinfo (roll_no, name, address, age) values (930, 'Trev', 'Apt 1404', 24);
insert into studentinfo (roll_no, name, address, age) values (931, 'Harwilll', 'PO Box 71042', 13);
insert into studentinfo (roll_no, name, address, age) values (932, 'Sal', 'PO Box 28879', 7);
insert into studentinfo (roll_no, name, address, age) values (933, 'Joan', 'Suite 74', null);
insert into studentinfo (roll_no, name, address, age) values (934, 'Goldie', 'Room 1949', 19);
insert into studentinfo (roll_no, name, address, age) values (935, 'Reggy', 'PO Box 70575', 15);
insert into studentinfo (roll_no, name, address, age) values (936, 'Lissi', 'PO Box 98165', 23);
insert into studentinfo (roll_no, name, address, age) values (937, 'Britte', '16th Floor', 12);
insert into studentinfo (roll_no, name, address, age) values (938, 'Christiana', 'Suite 61', null);
insert into studentinfo (roll_no, name, address, age) values (939, 'Abran', 'Room 1068', 21);
insert into studentinfo (roll_no, name, address, age) values (940, 'Arlyn', 'Suite 44', 21);
insert into studentinfo (roll_no, name, address, age) values (941, 'Stu', 'Apt 660', 6);
insert into studentinfo (roll_no, name, address, age) values (942, 'Chevy', 'PO Box 28574', 10);
insert into studentinfo (roll_no, name, address, age) values (943, 'Antonius', 'Suite 25', 22);
insert into studentinfo (roll_no, name, address, age) values (944, 'Corny', 'Suite 98', 18);
insert into studentinfo (roll_no, name, address, age) values (945, 'Brina', 'Room 866', 6);
insert into studentinfo (roll_no, name, address, age) values (946, 'Heather', 'PO Box 37681', null);
insert into studentinfo (roll_no, name, address, age) values (947, 'Karrah', 'PO Box 79768', 18);
insert into studentinfo (roll_no, name, address, age) values (948, 'Courtney', 'Apt 1430', null);
insert into studentinfo (roll_no, name, address, age) values (949, 'Dorelle', '9th Floor', null);
insert into studentinfo (roll_no, name, address, age) values (950, 'Aloise', '12th Floor', 23);
insert into studentinfo (roll_no, name, address, age) values (951, 'Heidi', 'Apt 1378', 13);
insert into studentinfo (roll_no, name, address, age) values (952, 'Cos', '15th Floor', 6);
insert into studentinfo (roll_no, name, address, age) values (953, 'Diana', '5th Floor', 20);
insert into studentinfo (roll_no, name, address, age) values (954, 'Thatcher', 'PO Box 25602', null);
insert into studentinfo (roll_no, name, address, age) values (955, 'Sascha', 'Apt 1032', null);
insert into studentinfo (roll_no, name, address, age) values (956, 'Ruthe', 'PO Box 80725', 6);
insert into studentinfo (roll_no, name, address, age) values (957, 'Cathe', 'Room 1635', 12);
insert into studentinfo (roll_no, name, address, age) values (958, 'Modestia', 'PO Box 59739', 21);
insert into studentinfo (roll_no, name, address, age) values (959, 'Hobey', 'PO Box 4941', 13);
insert into studentinfo (roll_no, name, address, age) values (960, 'Christiane', '17th Floor', 13);
insert into studentinfo (roll_no, name, address, age) values (961, 'Elfrieda', 'Suite 94', 7);
insert into studentinfo (roll_no, name, address, age) values (962, 'Frannie', 'Suite 79', null);
insert into studentinfo (roll_no, name, address, age) values (963, 'Saloma', '19th Floor', 23);
insert into studentinfo (roll_no, name, address, age) values (964, 'Torin', 'Apt 40', 16);
insert into studentinfo (roll_no, name, address, age) values (965, 'Maxim', 'Suite 84', 24);
insert into studentinfo (roll_no, name, address, age) values (966, 'Sharon', 'PO Box 82442', null);
insert into studentinfo (roll_no, name, address, age) values (967, 'Hartley', 'Apt 781', 16);
insert into studentinfo (roll_no, name, address, age) values (968, 'Anabella', 'Room 1907', 22);
insert into studentinfo (roll_no, name, address, age) values (969, 'Penni', 'PO Box 68101', null);
insert into studentinfo (roll_no, name, address, age) values (970, 'Cort', 'Suite 60', 23);
insert into studentinfo (roll_no, name, address, age) values (971, 'Max', 'PO Box 38090', 16);
insert into studentinfo (roll_no, name, address, age) values (972, 'Rockey', 'PO Box 43928', 22);
insert into studentinfo (roll_no, name, address, age) values (973, 'Nydia', 'Room 432', 16);
insert into studentinfo (roll_no, name, address, age) values (974, 'Gideon', 'PO Box 71086', null);
insert into studentinfo (roll_no, name, address, age) values (975, 'Maia', 'Room 388', 15);
insert into studentinfo (roll_no, name, address, age) values (976, 'Brietta', 'Apt 748', 6);
insert into studentinfo (roll_no, name, address, age) values (977, 'Leoine', 'PO Box 37230', 19);
insert into studentinfo (roll_no, name, address, age) values (978, 'Tod', 'PO Box 53293', 18);
insert into studentinfo (roll_no, name, address, age) values (979, 'Teodorico', 'Suite 16', 10);
insert into studentinfo (roll_no, name, address, age) values (980, 'Chilton', 'PO Box 72939', 15);
insert into studentinfo (roll_no, name, address, age) values (981, 'Zorah', '9th Floor', 24);
insert into studentinfo (roll_no, name, address, age) values (982, 'Nathanial', 'Apt 986', 18);
insert into studentinfo (roll_no, name, address, age) values (983, 'Mylo', 'PO Box 49911', 17);
insert into studentinfo (roll_no, name, address, age) values (984, 'Chan', '2nd Floor', 23);
insert into studentinfo (roll_no, name, address, age) values (985, 'Eden', 'Room 1066', 15);
insert into studentinfo (roll_no, name, address, age) values (986, 'Chaunce', 'PO Box 77894', 6);
insert into studentinfo (roll_no, name, address, age) values (987, 'Araldo', 'Apt 1754', 21);
insert into studentinfo (roll_no, name, address, age) values (988, 'Julianna', '7th Floor', 20);
insert into studentinfo (roll_no, name, address, age) values (989, 'Lucita', 'Room 568', 13);
insert into studentinfo (roll_no, name, address, age) values (990, 'Dulcia', 'Suite 39', 15);
insert into studentinfo (roll_no, name, address, age) values (991, 'Lissy', 'PO Box 63420', 12);
insert into studentinfo (roll_no, name, address, age) values (992, 'Jamey', 'Suite 27', 20);
insert into studentinfo (roll_no, name, address, age) values (993, 'Lucita', 'PO Box 30757', 9);
insert into studentinfo (roll_no, name, address, age) values (994, 'Peta', 'Room 125', 24);
insert into studentinfo (roll_no, name, address, age) values (995, 'Si', '12th Floor', 7);
insert into studentinfo (roll_no, name, address, age) values (996, 'Bronny', 'Apt 54', 6);
insert into studentinfo (roll_no, name, address, age) values (997, 'Mandi', 'Suite 55', 19);
insert into studentinfo (roll_no, name, address, age) values (998, 'Chalmers', '9th Floor', 24);
insert into studentinfo (roll_no, name, address, age) values (999, 'Etan', 'Room 669', 22);
insert into studentinfo (roll_no, name, address, age) values (1000, 'Anton', 'Suite 22', null);
